import type { Question } from './types'

export const CATEGORIES = [
  { id: 'spicy', label: 'Spicy', emoji: '🔥' },
  { id: 'funny', label: 'Funny', emoji: '😂' },
  { id: 'deep', label: 'Deep', emoji: '🧠' },
  { id: 'chaotic', label: 'Chaotic', emoji: '💀' },
  { id: 'romantic', label: 'Romantic', emoji: '💘' },
  { id: 'achievements', label: 'Achievements', emoji: '🏆' },
  { id: 'awkward', label: 'Awkward', emoji: '😬' },
  { id: 'bold', label: 'Bold', emoji: '🌶️' },
]

export const QUESTIONS: Question[] = [
  // 🔥 Spicy (50)
  { text: "Who would survive a reality TV show the longest?", textAr: "مين فينا بيصمد أطول واحد في برنامج رياليتي؟", category: "spicy" },
  { text: "Who has the most unread messages?", textAr: "مين عنده أكثر رسايل ما فتحها؟", category: "spicy" },
  { text: "Who would ghost someone without feeling bad?", textAr: "مين يطنّش واحد ويختفي وما يحس بأي ذنب؟", category: "spicy" },
  { text: "Who is most likely to have a secret they've never told anyone?", textAr: "مين أكثر واحد عنده سر ما قاله لأحد طول حياته؟", category: "spicy" },
  { text: "Who would win in an argument against a stranger?", textAr: "مين بيكسب أي مشادة مع شخص غريب؟", category: "spicy" },
  { text: "Who has sent the most regrettable text at 2am?", textAr: "مين أرسل أكثر رسالة ندم عليها الساعة ثنتين بالليل؟", category: "spicy" },
  { text: "Who is most likely to have a situationship right now?", textAr: "مين أكثر واحد ممكن يكون داخل في علاقة مو واضحة لا ارتباط ولا شي، الحين؟", category: "spicy" },
  { text: "Who would be the most dangerous person to give power to?", textAr: "مين لو أعطيناه سلطة بيصير أخطر واحد فينا؟", category: "spicy" },
  { text: "Who could charm their way out of any situation?", textAr: "مين يقدر يطلّع نفسه من أي موقف بكلامه الحلو؟", category: "spicy" },
  { text: "Who is secretly holding a grudge?", textAr: "مين فينا حاقد في سرّه وما يبيّن؟", category: "spicy" },
  { text: "Who has the messiest relationship history?", textAr: "مين عنده أكثر تاريخ علاقات مليان مشاكل ودراما؟", category: "spicy" },
  { text: "Who would be a terrible lawyer but win the case anyway?", textAr: "مين بيكون محامي فاشل بس يكسب القضية على أي حال؟", category: "spicy" },
  { text: "Who has the most controversial search history?", textAr: "مين عنده أكثر سجل بحث يفضح صاحبه؟", category: "spicy" },
  { text: "Who is most likely to start drama at a party?", textAr: "مين أكثر واحد يولّع مشاكل ودراما في الحفلة؟", category: "spicy" },
  { text: "Who flirts without realizing they're doing it?", textAr: "مين يغازل وهو أصلاً ما يدري إنه يغازل؟", category: "spicy" },
  { text: "Who would betray the group for money?", textAr: "مين يبيع الشلة كلها عشان فلوس؟", category: "spicy" },
  { text: "Who has the most situational morals?", textAr: "مين أخلاقه على حسب الموقف، تتغير على كيفه؟", category: "spicy" },
  { text: "Who is most likely to date someone wildly out of the group's expectations?", textAr: "مين أكثر واحد ممكن يرتبط بحد ما يخطر على بال أحد فينا أبداً؟", category: "spicy" },
  { text: "Who would survive the longest in a cult before catching on?", textAr: "مين بيقعد أطول واحد جوّا جماعة مغسّلين مخه قبل ما يفطن؟", category: "spicy" },
  { text: "Who has the most toxic trait they refuse to acknowledge?", textAr: "مين عنده أسوأ صفة سامّة ورافض يعترف فيها؟", category: "spicy" },
  { text: "Who has lied the most convincingly to get out of something?", textAr: "مين كذب أكذب كذبة مقنعة عشان يطلّع نفسه من شي؟", category: "spicy" },
  { text: "Who would make the scariest villain?", textAr: "مين لو صار شرير بيطلع أخوف وحش؟", category: "spicy" },
  { text: "Who gives advice they don't follow themselves?", textAr: "مين ينصح الناس بكلام هو نفسه ما يطبّقه؟", category: "spicy" },
  { text: "Who would be the first to expose a group secret?", textAr: "مين أول واحد بيفشي سر الشلة؟", category: "spicy" },
  { text: "Who needs the most external validation?", textAr: "مين أكثر واحد محتاج مدح الناس وتطمينهم عشان يرتاح؟", category: "spicy" },
  { text: "Who would be the most manipulative without trying to be?", textAr: "مين أكثر واحد يلعب على الناس ويتحكم فيهم وهو ما يقصد أصلاً؟", category: "spicy" },
  { text: "Who is most likely to slide into someone's DMs right now?", textAr: "مين أكثر واحد ممكن يرسل خاص لحد الحين عشان يبدأ معه؟", category: "spicy" },
  { text: "Who has had the most complicated friendship?", textAr: "مين عنده أكثر صداقة معقّدة ومليانة لخبطة؟", category: "spicy" },
  { text: "Who is most likely to have a double life nobody knows about?", textAr: "مين أكثر واحد ممكن يكون عايش حياة ثانية ولا أحد يدري عنها؟", category: "spicy" },
  { text: "Who would turn into a completely different person after one drink?", textAr: "مين يتغيّر ويصير شخص ثاني تماماً أول ما يشرب كاسة وحدة؟", category: "spicy" },
  { text: "Who is the most passive-aggressive when upset?", textAr: "مين أكثر واحد يزعل ويعبّر بطريقة ملتوية بدال ما يقولها بوجهك؟", category: "spicy" },
  { text: "Who would win a staring contest with anyone?", textAr: "مين يكسب مسابقة التحديق مع أي أحد؟", category: "spicy" },
  { text: "Who is most likely to be the villain in someone else's story?", textAr: "مين أكثر واحد ممكن يكون هو الشرير في قصة شخص ثاني؟", category: "spicy" },
  { text: "Who is carrying the most unresolved feelings?", textAr: "مين فينا حامل أكثر مشاعر مكبوتة ما خلّصها لين الحين؟", category: "spicy" },
  { text: "Who would be the most intimidating person in a negotiation?", textAr: "مين أكثر واحد يرعب الطرف الثاني وقت المفاوضات؟", category: "spicy" },
  { text: "Who would say \"I told you so\" the fastest?", textAr: "مين أسرع واحد يقول لك \"قلت لك؟ شفت؟\"؟", category: "spicy" },
  { text: "Who has the highest body count of situationships?", textAr: "مين عنده أكثر عدد علاقات مو واضحة دخل فيها وطلع؟", category: "spicy" },
  { text: "Who would thrive the most on the attention of someone they don't even like?", textAr: "مين يستمتع باهتمام شخص هو أصلاً ما يطيقه؟", category: "spicy" },
  { text: "Who is most likely to have a soft spot for someone terrible for them?", textAr: "مين أكثر واحد قلبه يلين لشخص مدمّر له وما يناسبه أبداً؟", category: "spicy" },
  { text: "Who would win a game of psychological chess?", textAr: "مين يكسب لعبة الشطرنج النفسية واللعب بعقول الناس؟", category: "spicy" },
  { text: "Who is most likely to have unfinished business with someone from their past?", textAr: "مين أكثر واحد عنده حسابات ما خلّصها مع أحد من ماضيه؟", category: "spicy" },
  { text: "Who holds grudges the longest?", textAr: "مين أطول واحد يحمل في قلبه ويحقد؟", category: "spicy" },
  { text: "Who would be most dangerous if they were actually angry?", textAr: "مين أخطر واحد لو زعل فعلاً وطلع عن طوره؟", category: "spicy" },
  { text: "Who is most likely to keep receipts on everyone?", textAr: "مين أكثر واحد يحفظ أدلّة وسوالف على كل أحد عشان يطلّعها وقت الحاجة؟", category: "spicy" },
  { text: "Who would last the longest pretending everything is fine?", textAr: "مين أطول واحد يتظاهر إن كل شي تمام وهو من جوّا مهدوم؟", category: "spicy" },
  { text: "Who would be the most convincing liar in an interrogation?", textAr: "مين أكثر واحد يكذب بإقناع لو حطّوه في تحقيق؟", category: "spicy" },
  { text: "Who has the most skeletons in their closet?", textAr: "مين عنده أكثر أسرار وفضايح مدفونة ومخبّيها؟", category: "spicy" },
  { text: "Who would snap the most dramatically?", textAr: "مين لو انفجر بينفجر بأكثر طريقة دراماتيكية؟", category: "spicy" },
  { text: "Who is most likely to be the reason someone goes to therapy?", textAr: "مين أكثر واحد ممكن يكون هو السبب إن أحد يروح لدكتور نفسي؟", category: "spicy" },
  { text: "Who could make someone fall for them without even trying?", textAr: "مين يقدر يخلي أحد يقع في حبه وهو أصلاً ما سوّى شي؟", category: "spicy" },

  // 😂 Funny (50)
  { text: "Who laughs at their own jokes the most?", textAr: "مين فينا أكثر واحد يضحك على نكته هو؟", category: "funny" },
  { text: "Who would trip walking up to accept an award?", textAr: "مين اللي بيتعثر وهو طالع ياخذ جايزة قدام الناس؟", category: "funny" },
  { text: "Who would accidentally text the wrong person something embarrassing?", textAr: "مين اللي يرسل شي محرج بالغلط لشخص ثاني؟", category: "funny" },
  { text: "Who takes the longest to get ready?", textAr: "مين فينا ياخذ أطول وقت عشان يجهز ويطلع؟", category: "funny" },
  { text: "Who is most likely to forget someone's name mid-conversation?", textAr: "مين أكثر واحد ينسى اسم اللي قدامه وهو يكلمه؟", category: "funny" },
  { text: "Who would accidentally like a photo from 3 years ago?", textAr: "مين اللي يضغط لايك بالغلط على صورة لها ٣ سنين؟", category: "funny" },
  { text: "Who would order the wrong thing and eat it anyway?", textAr: "مين اللي يطلب شي غلط ومع ذلك ياكله ويسكت؟", category: "funny" },
  { text: "Who would get into a heated debate about something completely trivial?", textAr: "مين اللي يدخل في نقاش وحماس على شي تافه ما يسوى؟", category: "funny" },
  { text: "Who would get lost following GPS directions?", textAr: "مين اللي يتوه حتى وهو ماشي على الخرايط؟", category: "funny" },
  { text: "Who has the most chaotic morning routine?", textAr: "مين فينا صباحه فوضى ومقلب من أول ما يصحى؟", category: "funny" },
  { text: "Who would say something awkward during a toast?", textAr: "مين اللي يقول كلمة محرجة وهو يلقي كلمة بالمناسبة؟", category: "funny" },
  { text: "Who would wear pajamas to an event if they could?", textAr: "مين اللي لو يقدر بيروح المناسبة بالبيجامه؟", category: "funny" },
  { text: "Who would walk into a glass door?", textAr: "مين اللي يخبط في باب الزجاج لأنه ما شافه؟", category: "funny" },
  { text: "Who has the funniest \"I thought I had it under control\" story?", textAr: "مين عنده أضحك موقف من نوع «كنت حاسب الأمور تحت السيطرة»؟", category: "funny" },
  { text: "Who is most likely to burn water?", textAr: "مين أكثر واحد يقدر يحرق حتى الماي وهو يطبخ؟", category: "funny" },
  { text: "Who would mispronounce something in front of an expert?", textAr: "مين اللي ينطق كلمة غلط قدام واحد خبير في المجال؟", category: "funny" },
  { text: "Who would confidently give wrong directions to a tourist?", textAr: "مين اللي يدل سايح على الطريق غلط وهو واثق من نفسه؟", category: "funny" },
  { text: "Who would sneeze at the worst possible moment?", textAr: "مين اللي يعطس في أسوأ لحظة ممكنة؟", category: "funny" },
  { text: "Who would buy something they've never used and leave it in a drawer forever?", textAr: "مين اللي يشتري شي وما يستخدمه أبد ويرميه في الدرج للأبد؟", category: "funny" },
  { text: "Who would talk during a movie and claim they weren't?", textAr: "مين اللي يتكلم طول الفلم وبعدين يقول «أنا ما تكلمت»؟", category: "funny" },
  { text: "Who is most likely to be the reason a group plan falls apart?", textAr: "مين أكثر واحد يكون هو السبب إن خطة الشلة تخرب؟", category: "funny" },
  { text: "Who would accidentally reply-all to an email?", textAr: "مين اللي يرد على الكل بالغلط في الإيميل؟", category: "funny" },
  { text: "Who would try to fix something and make it significantly worse?", textAr: "مين اللي يجي يصلح شي ويخربه أكثر بكثير؟", category: "funny" },
  { text: "Who would laugh at a funeral?", textAr: "مين اللي ممكن يضحك وهو في عزا؟", category: "funny" },
  { text: "Who would show up to the wrong address with full confidence?", textAr: "مين اللي يوصل عنوان غلط وهو واثق إنه صح؟", category: "funny" },
  { text: "Who is most likely to auto-correct a message into something chaotic?", textAr: "مين أكثر واحد التصحيح التلقائي يقلب رسالته لشي مقلب؟", category: "funny" },
  { text: "Who would dramatically overreact to a bug?", textAr: "مين اللي يصير عنده دراما ويبالغ لما يشوف حشرة؟", category: "funny" },
  { text: "Who would fall asleep during an important event?", textAr: "مين اللي ينام في مناسبة مهمة؟", category: "funny" },
  { text: "Who would absolutely destroy everyone at karaoke?", textAr: "مين اللي بيكسّر الكل ويبدع في الكاريوكي؟", category: "funny" },
  { text: "Who would lose track of time and show up an hour late, guilt-free?", textAr: "مين اللي ينسى الوقت ويجي متأخر ساعة وما عنده أي إحساس بالذنب؟", category: "funny" },
  { text: "Who would challenge someone to a race and immediately regret it?", textAr: "مين اللي يتحدى واحد على سباق ويندم على طول؟", category: "funny" },
  { text: "Who would accidentally join the wrong group chat?", textAr: "مين اللي يدخل قروب غلط من غير ما ينتبه؟", category: "funny" },
  { text: "Who is most likely to mispronounce a word they've only ever read?", textAr: "مين أكثر واحد ينطق كلمة غلط لأنه قاريها بس ما سمعها؟", category: "funny" },
  { text: "Who would narrate their own life like a documentary?", textAr: "مين اللي يعلّق على حياته كأنه في فلم وثائقي؟", category: "funny" },
  { text: "Who would eat something weird and ask what it was only after finishing?", textAr: "مين اللي ياكل شي غريب وبعد ما يخلص يسأل وش كان؟", category: "funny" },
  { text: "Who would try to be cool in front of a celebrity and completely fail?", textAr: "مين اللي يحاول يبين كوول قدام مشهور ويفشل تماماً؟", category: "funny" },
  { text: "Who would panic-buy the most during a sale?", textAr: "مين أكثر واحد يشتري بهبل وهلع في وقت التخفيضات؟", category: "funny" },
  { text: "Who would lose a staring contest in under 5 seconds?", textAr: "مين اللي يخسر تحدي النظرات في أقل من ٥ ثواني؟", category: "funny" },
  { text: "Who would sing out loud without realizing others can hear them?", textAr: "مين اللي يغني بصوت عالي وهو ما داري إن الناس تسمعه؟", category: "funny" },
  { text: "Who sends the most chaotic voice notes?", textAr: "مين فينا يرسل أكثر مقاطع صوتية مخربطة ومقلب؟", category: "funny" },
  { text: "Who would forget they asked a question and ask it again?", textAr: "مين اللي ينسى إنه سأل سؤال ويعيده مرة ثانية؟", category: "funny" },
  { text: "Who has the most chaotic notes app?", textAr: "مين فينا تطبيق الملاحظات حقه أكثر شي مخربط وفوضى؟", category: "funny" },
  { text: "Who would arrive somewhere and immediately want to leave?", textAr: "مين اللي يوصل مكان ويبي يطلع منه على طول؟", category: "funny" },
  { text: "Who would save every meme but never send them to anyone?", textAr: "مين اللي يحفظ كل الميمز وما يرسلها لأحد أبد؟", category: "funny" },
  { text: "Who would google something obvious and not tell anyone?", textAr: "مين اللي يبحث في قوقل عن شي واضح وما يقول لأحد؟", category: "funny" },
  { text: "Who has an embarrassing playlist they'd die if anyone saw?", textAr: "مين عنده قائمة أغاني محرجة لو أحد شافها بيموت من الكسوف؟", category: "funny" },
  { text: "Who would start a story with \"this is so funny\" and then tell a terrible story?", textAr: "مين اللي يبدأ قصته بـ«والله شي يضحك» وبعدين يطلع موضوع ممل وسخيف؟", category: "funny" },
  { text: "Who would break something at someone's house and say nothing?", textAr: "مين اللي يكسر شي في بيت أحد ويسكت وما يقول؟", category: "funny" },
  { text: "Who would think they're whispering but absolutely aren't?", textAr: "مين اللي حاسب نفسه يهمس بس صوته طالع للكل؟", category: "funny" },
  { text: "Who would try to sneak food into somewhere and get caught immediately?", textAr: "مين اللي يحاول يهرّب أكل لمكان ويمسكونه على طول؟", category: "funny" },

  // 🧠 Deep (50)
  { text: "Who thinks about life's meaning the most?", textAr: "مين فينا أكثر واحد يفكر في معنى الحياة؟", category: "deep" },
  { text: "Who would write a book someday?", textAr: "مين فينا اللي يمكن يكتب كتاب يوم من الأيام؟", category: "deep" },
  { text: "Who feels things more deeply than they show?", textAr: "مين فينا يحس بالأشياء أعمق بكثير من اللي يبيّنه؟", category: "deep" },
  { text: "Who is most likely to change the world?", textAr: "مين فينا أكثر واحد يقدر يغيّر العالم؟", category: "deep" },
  { text: "Who has the most complex inner world?", textAr: "مين فينا عالمه الداخلي أكثر واحد معقّد؟", category: "deep" },
  { text: "Who questions everything they've been taught?", textAr: "مين فينا يشكّك في كل شي تربّى وتعلّم عليه؟", category: "deep" },
  { text: "Who would be the most transformative teacher?", textAr: "مين فينا لو صار مدرّس بيغيّر حياة طلابه أكثر واحد؟", category: "deep" },
  { text: "Who carries the weight of other people's problems?", textAr: "مين فينا يشيل هموم الناس ومشاكلهم على كتفه؟", category: "deep" },
  { text: "Who is quietly figuring out their purpose?", textAr: "مين فينا بالسر قاعد يدوّر على هدفه في الحياة؟", category: "deep" },
  { text: "Who would be the wisest at age 80?", textAr: "مين فينا بيكون أحكم واحد لما يصير عمره ٨٠؟", category: "deep" },
  { text: "Who has had the most formative life experience?", textAr: "مين فينا مرّ بتجربة في حياته غيّرته أكثر من أي أحد؟", category: "deep" },
  { text: "Who sees patterns others miss?", textAr: "مين فينا يربط الأمور ويلاحظ أشياء الباقين ما ينتبهون لها؟", category: "deep" },
  { text: "Who is most likely to have a profound conversation at 3am?", textAr: "مين فينا أكثر واحد يدخل في كلام عميق الساعة ٣ بالليل؟", category: "deep" },
  { text: "Who thinks about their legacy the most?", textAr: "مين فينا أكثر واحد يفكر وش بيخلّي وراه بعد ما يروح؟", category: "deep" },
  { text: "Who has the most well-developed moral code?", textAr: "مين فينا مبادئه وأخلاقه أكثر واحد واضحة وثابتة؟", category: "deep" },
  { text: "Who would be the most introspective after a hard experience?", textAr: "مين فينا بعد تجربة صعبة يقعد يحاسب نفسه ويفكّر أكثر واحد؟", category: "deep" },
  { text: "Who has grown the most in the last few years?", textAr: "مين فينا تطوّر ونضج أكثر واحد في السنوات اللي راحت؟", category: "deep" },
  { text: "Who would give the best life advice to a stranger?", textAr: "مين فينا يعطي أحلى نصيحة في الحياة حتى لشخص غريب ما يعرفه؟", category: "deep" },
  { text: "Who is most in touch with who they really are?", textAr: "مين فينا أكثر واحد فاهم نفسه ويعرف هو منو بالضبط؟", category: "deep" },
  { text: "Who has the clearest sense of what they want from life?", textAr: "مين فينا أكثر واحد عارف بالضبط وش يبي من الحياة؟", category: "deep" },
  { text: "Who would be the most self-aware person in a therapy session?", textAr: "مين فينا لو راح للأخصائي النفسي بيكون أكثر واحد فاهم نفسه؟", category: "deep" },
  { text: "Who would forgive the hardest thing to forgive?", textAr: "مين فينا يقدر يسامح على أصعب شي ما ينسامح عليه؟", category: "deep" },
  { text: "Who is most likely to cry at something unexpected?", textAr: "مين فينا أكثر واحد تجيه دمعته من شي ما يتوقعه أبد؟", category: "deep" },
  { text: "Who notices things others don't pay attention to?", textAr: "مين فينا يلاحظ تفاصيل الباقين ما يعطونها أي بال؟", category: "deep" },
  { text: "Who would handle grief the most quietly?", textAr: "مين فينا لو فقد أحد يتحمّل حزنه بهدوء وبالسكوت أكثر واحد؟", category: "deep" },
  { text: "Who is carrying something they haven't said out loud yet?", textAr: "مين فينا شايل في صدره شي لين الحين ما طلّعه ولا قاله لأحد؟", category: "deep" },
  { text: "Who would write the most honest journal entry?", textAr: "مين فينا لو كتب في دفتره يكتب أصدق كلام من قلبه؟", category: "deep" },
  { text: "Who has the most defined sense of home?", textAr: "مين فينا معنى البيت والوطن عنده أكثر واحد واضح وراسخ؟", category: "deep" },
  { text: "Who is most likely to reinvent themselves completely?", textAr: "مين فينا أكثر واحد يقدر يغيّر نفسه ويبدأ من جديد بالكامل؟", category: "deep" },
  { text: "Who makes people feel the most seen?", textAr: "مين فينا يخلّي الناس تحس إن أحد فاهمها وشايفها فعلاً؟", category: "deep" },
  { text: "Who would be most at peace with an uncertain future?", textAr: "مين فينا أكثر واحد مرتاح وما يقلق حتى لو المستقبل مو واضح؟", category: "deep" },
  { text: "Who has the most nuanced opinions on complicated topics?", textAr: "مين فينا آراؤه في المواضيع المعقّدة أكثر واحد عميقة وما تاخذ جانب واحد؟", category: "deep" },
  { text: "Who would sit with their own silence the best?", textAr: "مين فينا يقدر يقعد مع نفسه بصمت وارتياح أكثر واحد؟", category: "deep" },
  { text: "Who is most likely to choose meaning over money?", textAr: "مين فينا أكثر واحد يختار الشي اللي له معنى على الفلوس؟", category: "deep" },
  { text: "Who grieves things that others move on from quickly?", textAr: "مين فينا يضل حزين على أشياء الباقين تجاوزوها بسرعة؟", category: "deep" },
  { text: "Who has the most unresolved inner conflict?", textAr: "مين فينا عنده صراع داخلي لين الحين ما حلّه أكثر واحد؟", category: "deep" },
  { text: "Who would be the first to admit they were wrong?", textAr: "مين فينا أول واحد يعترف إنه غلطان؟", category: "deep" },
  { text: "Who most deeply understands someone else in this group?", textAr: "مين فينا أكثر واحد فاهم شخص ثاني من الجماعة من جوّه؟", category: "deep" },
  { text: "Who would turn pain into something beautiful?", textAr: "مين فينا يقدر يحوّل وجعه وألمه لشي حلو؟", category: "deep" },
  { text: "Who is most likely to find profound meaning in small moments?", textAr: "مين فينا أكثر واحد يلقى معنى عميق في أبسط اللحظات؟", category: "deep" },
  { text: "Who would be the most honest in an autobiography?", textAr: "مين فينا لو كتب سيرته الذاتية بيكون أصدق واحد فيها؟", category: "deep" },
  { text: "Who thinks the most about the people they've lost touch with?", textAr: "مين فينا أكثر واحد يفكر في الناس اللي انقطع عنهم؟", category: "deep" },
  { text: "Who is most likely to leave everything behind and start fresh?", textAr: "مين فينا أكثر واحد يقدر يترك كل شي ورا ظهره ويبدأ من الصفر؟", category: "deep" },
  { text: "Who asks the best questions?", textAr: "مين فينا يسأل أحلى الأسئلة؟", category: "deep" },
  { text: "Who feels most connected to something bigger than themselves?", textAr: "مين فينا أكثر واحد حاسّ إنه مرتبط بشي أكبر منه؟", category: "deep" },
  { text: "Who is most changed by the books or stories they consume?", textAr: "مين فينا الكتب والقصص اللي يقراها تأثّر فيه وتغيّره أكثر واحد؟", category: "deep" },
  { text: "Who would understand a stranger's perspective the fastest?", textAr: "مين فينا أسرع واحد يفهم وجهة نظر شخص غريب ويحطّ نفسه مكانه؟", category: "deep" },
  { text: "Who has the most considered relationship with their past?", textAr: "مين فينا أكثر واحد متصالح مع ماضيه وفاهمه؟", category: "deep" },
  { text: "Who would be the hardest to truly know?", textAr: "مين فينا أصعب واحد تعرفه على حقيقته؟", category: "deep" },
  { text: "Who will look back on this period of life the most fondly?", textAr: "مين فينا بعد سنين بيتذكر هالفترة من حياته بأحلى الذكريات؟", category: "deep" },

  // 💀 Chaotic (50)
  { text: "Who would start a fire (accidentally) at a party?", textAr: "مين فينا يقدر يشعل حريق بالغلط في حفلة؟", category: "chaotic" },
  { text: "Who makes decisions by flipping a coin?", textAr: "مين فينا ياخذ قراراته برمي عملة، صورة وإلا كتابة؟", category: "chaotic" },
  { text: "Who would show up to a formal event underdressed?", textAr: "مين فينا يجي مناسبة رسمية وهو لابس عادي ومب على القد؟", category: "chaotic" },
  { text: "Who is one bad day away from moving to another country?", textAr: "مين فينا ناقصه يوم خايس ويقرر يهاجر لدولة ثانية؟", category: "chaotic" },
  { text: "Who has the most chaotic phone camera roll?", textAr: "مين أكثر واحد فينا ألبوم صوره في الجوال مخربط وفوضى؟", category: "chaotic" },
  { text: "Who would agree to something without reading the fine print?", textAr: "مين فينا يوافق على شي وهو ما قرأ الشروط ولا الكلام الصغير؟", category: "chaotic" },
  { text: "Who would give terrible directions but be fully confident?", textAr: "مين فينا يدلك على طريق غلط وهو واثق من نفسه عدل؟", category: "chaotic" },
  { text: "Who would mix drinks at a party and call it a \"signature cocktail\"?", textAr: "مين فينا يخلط عصيرات ومشروبات في حفلة ويسميها \"الخلطة الخاصة حقته\"؟", category: "chaotic" },
  { text: "Who would spontaneously adopt a pet?", textAr: "مين فينا فجأة وبدون تفكير ياخذ له حيوان أليف؟", category: "chaotic" },
  { text: "Who would start five projects and finish none of them?", textAr: "مين فينا يبدأ خمس مشاريع وما يخلّص ولا وحدة منها؟", category: "chaotic" },
  { text: "Who would reorganize a room and make it worse?", textAr: "مين فينا يرتب الغرفة من جديد ويطلعها أسوأ من قبل؟", category: "chaotic" },
  { text: "Who would walk into the wrong room and just go with it?", textAr: "مين فينا يدخل غرفة غلط ويكمّل عادي كأن شي ما صار؟", category: "chaotic" },
  { text: "Who would quit their job on a random Tuesday with no backup plan?", textAr: "مين فينا يستقيل من شغله يوم ثلاثاء عادي وما عنده ولا خطة بديلة؟", category: "chaotic" },
  { text: "Who would book a flight on impulse?", textAr: "مين فينا يحجز تذكرة طيران فجأة وبدون ما يفكر؟", category: "chaotic" },
  { text: "Who has the most unhinged notes in their phone?", textAr: "مين أكثر واحد فينا ملاحظاته في الجوال غريبة ومجنونة؟", category: "chaotic" },
  { text: "Who would rearrange everyone's furniture while they're sleeping?", textAr: "مين فينا يغيّر ترتيب أثاث الكل وهم نايمين؟", category: "chaotic" },
  { text: "Who would make a major life decision based on a horoscope?", textAr: "مين فينا ياخذ قرار كبير في حياته بناءً على الأبراج؟", category: "chaotic" },
  { text: "Who would start a group project the night before?", textAr: "مين فينا يبدأ المشروع الجماعي ليلة التسليم؟", category: "chaotic" },
  { text: "Who would forget where they parked and report their car stolen?", textAr: "مين فينا ينسى وين ركّن سيارته ويبلّغ إنها مسروقة؟", category: "chaotic" },
  { text: "Who is most likely to have three unfinished online shopping carts?", textAr: "مين أكثر واحد فينا عنده ثلاث سلات تسوق ما خلّصها؟", category: "chaotic" },
  { text: "Who would download 10 apps, use none of them, and delete them all?", textAr: "مين فينا ينزّل عشر تطبيقات وما يفتح ولا وحدة ويمسحها كلها؟", category: "chaotic" },
  { text: "Who would let autocorrect send something truly unhinged?", textAr: "مين فينا يخلّي التصحيح التلقائي يرسل كلام غريب ومجنون؟", category: "chaotic" },
  { text: "Who would wake up and immediately make a chaotic decision?", textAr: "مين فينا أول ما يصحى من النوم ياخذ قرار مخبص على طول؟", category: "chaotic" },
  { text: "Who would set five alarms and sleep through all of them?", textAr: "مين فينا يحط خمس منبهات وينام عليهم كلهم؟", category: "chaotic" },
  { text: "Who is most likely to take a random exit on a road trip and just see what happens?", textAr: "مين أكثر واحد فينا في رحلة بالسيارة ياخذ مخرج عشوائي بس عشان يشوف وش بيصير؟", category: "chaotic" },
  { text: "Who would impulse-buy something massive and regret it immediately?", textAr: "مين فينا يشتري شي كبير بدون تفكير ويندم على طول؟", category: "chaotic" },
  { text: "Who would RSVP yes to two conflicting events and deal with it later?", textAr: "مين فينا يقول حاضر لمناسبتين بنفس الوقت ويتصرف بعدين؟", category: "chaotic" },
  { text: "Who would try to fix the Wi-Fi and accidentally reset everyone's settings?", textAr: "مين فينا يبي يصلّح الواي فاي ويفرمت إعدادات الكل بالغلط؟", category: "chaotic" },
  { text: "Who would go down a rabbit hole at 1am and emerge with a new obsession?", textAr: "مين فينا الساعة وحدة بالليل يبدأ يبحث في شي ويطلع عنده هوس جديد؟", category: "chaotic" },
  { text: "Who would be the last to realize the plan changed?", textAr: "مين فينا آخر واحد يدري إن الخطة تغيرت؟", category: "chaotic" },
  { text: "Who has the most \"I can fix it\" energy about things they can't fix?", textAr: "مين أكثر واحد فينا يقول \"أنا أصلّحها\" لأشياء ما يقدر يصلّحها؟", category: "chaotic" },
  { text: "Who would start a diet on a Thursday?", textAr: "مين فينا يبدأ رجيم يوم خميس؟", category: "chaotic" },
  { text: "Who would confidently assemble furniture and have pieces left over?", textAr: "مين فينا يركّب أثاث وهو واثق ويطلع عنده قطع زايدة؟", category: "chaotic" },
  { text: "Who would invite too many people to something and not tell anyone?", textAr: "مين فينا يعزم ناس وايد على شي وما يخبر أحد؟", category: "chaotic" },
  { text: "Who would get distracted on an errand and come back with something completely different?", textAr: "مين فينا يطلع يجيب شي وينلهى ويرجع بشي ثاني تماماً؟", category: "chaotic" },
  { text: "Who is most likely to lose their keys, wallet, and phone in the same day?", textAr: "مين أكثر واحد فينا يضيّع مفاتيحه ومحفظته وجواله في نفس اليوم؟", category: "chaotic" },
  { text: "Who would start redecorating at midnight?", textAr: "مين فينا يبدأ يغير ديكور البيت نص الليل؟", category: "chaotic" },
  { text: "Who would \"quickly check something\" and disappear for 45 minutes?", textAr: "مين فينا يقول \"بس بشوف شي بسرعة\" ويختفي ٤٥ دقيقة؟", category: "chaotic" },
  { text: "Who would name a pet something unhinged?", textAr: "مين فينا يسمّي حيوانه الأليف اسم غريب ومجنون؟", category: "chaotic" },
  { text: "Who would send a 3-minute voice note when a one-word answer was needed?", textAr: "مين فينا يرسل مقطع صوتي ثلاث دقايق والجواب كان كلمة وحدة بس؟", category: "chaotic" },
  { text: "Who is most likely to accidentally break something they just bought?", textAr: "مين أكثر واحد فينا يكسر شي للتو شراه بالغلط؟", category: "chaotic" },
  { text: "Who would read a 5-step recipe and freestyle from step 2?", textAr: "مين فينا يقرأ وصفة من خمس خطوات ويبدأ يرتجل من الخطوة الثانية؟", category: "chaotic" },
  { text: "Who would cancel plans, feel relieved, and then immediately make new plans?", textAr: "مين فينا يلغي خطته ويرتاح وبعدها على طول يسوي خطة جديدة؟", category: "chaotic" },
  { text: "Who would save a spider in a cup and forget about it for three days?", textAr: "مين فينا يحبس عنكبوت في كوب وينساه ثلاثة أيام؟", category: "chaotic" },
  { text: "Who would get 40 tabs open and refuse to close any of them?", textAr: "مين فينا يفتح أربعين تبويب في المتصفح ويرفض يسكّر ولا وحد؟", category: "chaotic" },
  { text: "Who would sign up for a class, go once, and never return?", textAr: "مين فينا يسجّل في دورة ويروح مرة وحدة وما يرجع أبداً؟", category: "chaotic" },
  { text: "Who would move furniture alone at 11pm because they \"couldn't sleep\"?", textAr: "مين فينا ينقل الأثاث لحاله الساعة ١١ بالليل عشان \"ما جاه النوم\"؟", category: "chaotic" },
  { text: "Who has sent the most unhinged group chat message?", textAr: "مين فينا أرسل أغرب وأمجن رسالة في القروب؟", category: "chaotic" },
  { text: "Who would start explaining something and completely lose track of the point?", textAr: "مين فينا يبدأ يشرح شي وينسى وش كان قصده أصلاً؟", category: "chaotic" },
  { text: "Who would order something entirely different from what they said they wanted?", textAr: "مين فينا يطلب شي مختلف تماماً عن اللي قال إنه يبيه؟", category: "chaotic" },

  // 💘 Romantic (50)
  { text: "Who falls in love too easily?", textAr: "مين فينا يقع في الحب بسرعة وبسهولة؟", category: "romantic" },
  { text: "Who would plan the most elaborate date?", textAr: "مين بيجهز أحلى وأرتب موعد رومانسي؟", category: "romantic" },
  { text: "Who is most likely to have a crush right now?", textAr: "مين فينا أكثر واحد ممكن يكون معجب بأحد الحين؟", category: "romantic" },
  { text: "Who gives the best relationship advice but ignores it themselves?", textAr: "مين أحسن واحد ينصح في العلاقات بس هو نفسه ما يطبّق كلامه؟", category: "romantic" },
  { text: "Who would write love letters?", textAr: "مين فينا يكتب رسايل حب؟", category: "romantic" },
  { text: "Who has the most romantic soul?", textAr: "مين أكثر واحد فينا روحه رومانسية؟", category: "romantic" },
  { text: "Who would put the most thought into a gift?", textAr: "مين أكثر واحد يفكّر ويتعب على الهدية؟", category: "romantic" },
  { text: "Who would say \"I love you\" first?", textAr: "مين أول واحد فينا يقول \"أحبك\"؟", category: "romantic" },
  { text: "Who would stay up all night talking on a first date?", textAr: "مين يسهر الليل كله يتكلم في أول موعد؟", category: "romantic" },
  { text: "Who is most likely to have a Pinterest wedding board?", textAr: "مين فينا أكثر وحدة عندها بورد كامل لزواجها على بنترست؟", category: "romantic" },
  { text: "Who would serenade someone without a shred of embarrassment?", textAr: "مين يقدر يغني لأحد قدام الناس وما يستحي أبد؟", category: "romantic" },
  { text: "Who has the most romantic movie-worthy backstory?", textAr: "مين عنده قصة حب رومانسية تستاهل يتسوى لها فلم؟", category: "romantic" },
  { text: "Who would be most affected by a breakup?", textAr: "مين أكثر واحد فينا بينهد لو انفصل عن أحد؟", category: "romantic" },
  { text: "Who would make the most effort to keep a long-distance relationship alive?", textAr: "مين أكثر واحد بيتعب عشان يخلي العلاقة عن بُعد تستمر؟", category: "romantic" },
  { text: "Who re-reads old messages from people they liked?", textAr: "مين يرجع يقرا الرسايل القديمة حق ناس كان معجب فيهم؟", category: "romantic" },
  { text: "Who would be the best at making someone feel special on an ordinary day?", textAr: "مين أحسن واحد يخلي الشخص يحس إنه مميز في يوم عادي؟", category: "romantic" },
  { text: "Who would plan a surprise that makes someone genuinely emotional?", textAr: "مين بيسوي مفاجأة تخلي الشخص يتأثر من قلبه؟", category: "romantic" },
  { text: "Who would show up with flowers for no reason?", textAr: "مين يجي ومعاه ورد من دون أي مناسبة؟", category: "romantic" },
  { text: "Who would remember the tiny details a partner mentioned months ago?", textAr: "مين يتذكر أصغر التفاصيل اللي قالها شريكه من شهور؟", category: "romantic" },
  { text: "Who still believes in the idea of \"the one\"?", textAr: "مين لين الحين مؤمن بفكرة إن في \"شخص واحد مكتوب له\"؟", category: "romantic" },
  { text: "Who would make a playlist for someone they like?", textAr: "مين يسوي قائمة أغاني حق شخص معجب فيه؟", category: "romantic" },
  { text: "Who would be the most heartbroken after a falling out with a close friend?", textAr: "مين أكثر واحد بينكسر قلبه لو زعل مع صديق قريب منه؟", category: "romantic" },
  { text: "Who would cry at a romantic movie scene without admitting it?", textAr: "مين يبكي على مشهد رومانسي في فلم بس ما يعترف؟", category: "romantic" },
  { text: "Who would be the most devoted partner?", textAr: "مين بيكون أكثر شريك مخلص ومتفاني؟", category: "romantic" },
  { text: "Who would love too much too fast?", textAr: "مين يحب زود وبسرعة من أول؟", category: "romantic" },
  { text: "Who notices small romantic gestures that others miss?", textAr: "مين ينتبه للمسات الرومانسية الصغيرة اللي الكل يفوّتها؟", category: "romantic" },
  { text: "Who would choose a slow dance over a wild night out?", textAr: "مين يفضّل رقصة هادية على سهرة وطلعة هيصة؟", category: "romantic" },
  { text: "Who is most likely to fall for someone who is completely wrong for them?", textAr: "مين أكثر واحد ممكن يحب شخص غلط عليه تماماً؟", category: "romantic" },
  { text: "Who would never settle for anything less than butterflies?", textAr: "مين ما يرضى إلا بالحب اللي يخلي قلبه يرفرف؟", category: "romantic" },
  { text: "Who would be the most affectionate partner?", textAr: "مين بيكون أكثر شريك حنون ودلوع؟", category: "romantic" },
  { text: "Who would keep a photo of someone they liked years after it ended?", textAr: "مين يحتفظ بصورة شخص كان معجب فيه حتى بعد ما خلصت بسنين؟", category: "romantic" },
  { text: "Who would choose love over a career opportunity?", textAr: "مين يختار الحب على فرصة في شغله؟", category: "romantic" },
  { text: "Who is most likely to get emotional over an anniversary?", textAr: "مين أكثر واحد يتأثر ويصير عاطفي في ذكرى مناسبة؟", category: "romantic" },
  { text: "Who would send the most thoughtful morning text?", textAr: "مين يرسل أحلى وأرق رسالة صباح الخير؟", category: "romantic" },
  { text: "Who would still be curious about an old flame?", textAr: "مين لين الحين فضولي ويبي يعرف أخبار حب قديم؟", category: "romantic" },
  { text: "Who would fall for someone who wasn't their usual type?", textAr: "مين يحب شخص مو من نوعه اللي يحبه عادةً؟", category: "romantic" },
  { text: "Who gives the best hugs?", textAr: "مين أحضانه أحلى وأدفأ واحد فينا؟", category: "romantic" },
  { text: "Who has loved someone deeply but never told them?", textAr: "مين حب أحد من كل قلبه بس عمره ما قال له؟", category: "romantic" },
  { text: "Who would walk someone home just to spend more time with them?", textAr: "مين يوصّل أحد لين البيت بس عشان يقعد معاه أكثر؟", category: "romantic" },
  { text: "Who values loyalty the most in a relationship?", textAr: "مين أكثر واحد يهمه الوفا والإخلاص في العلاقة؟", category: "romantic" },
  { text: "Who would be the most patient with a difficult partner?", textAr: "مين أكثر واحد يصبر على شريك صعب ومتعب؟", category: "romantic" },
  { text: "Who would plan a romantic picnic completely from scratch?", textAr: "مين يجهّز بكنك رومانسي من الصفر بنفسه؟", category: "romantic" },
  { text: "Who is most likely to say \"I miss you\" first?", textAr: "مين أول واحد فينا يقول \"اشتقت لك\"؟", category: "romantic" },
  { text: "Who would still get butterflies from a simple text?", textAr: "مين لين الحين قلبه يرفرف من مجرد رسالة بسيطة؟", category: "romantic" },
  { text: "Who would drop everything to be there for someone they love?", textAr: "مين يترك كل شي عشان يكون جنب الشخص اللي يحبه؟", category: "romantic" },
  { text: "Who would be most affected by a song that reminds them of someone?", textAr: "مين أكثر واحد يتأثر من أغنية تذكّره بشخص؟", category: "romantic" },
  { text: "Who would make the most romantic grand gesture?", textAr: "مين بيسوي أكبر وأرومنسي موقف عشان يعبّر عن حبه؟", category: "romantic" },
  { text: "Who is most likely to marry their best friend?", textAr: "مين أكثر واحد ممكن يتزوج صديقه المقرّب؟", category: "romantic" },
  { text: "Who would love harder than anyone expects?", textAr: "مين يحب بقوة وعمق أكثر مما يتوقع منه أحد؟", category: "romantic" },
  { text: "Who would still believe in love after getting their heart broken?", textAr: "مين لين الحين يؤمن بالحب حتى بعد ما انكسر قلبه؟", category: "romantic" },

  // 🏆 Achievements (50)
  { text: "Who is most likely to become famous?", textAr: "مين فينا أكثر واحد ممكن يصير مشهور؟", category: "achievements" },
  { text: "Who was (or still is) the teacher's favorite?", textAr: "مين كان (أو لين الحين) المدلّع عند المدرّس؟", category: "achievements" },
  { text: "Who would be most successful in 10 years?", textAr: "مين فينا بيكون أنجح واحد بعد ١٠ سنين؟", category: "achievements" },
  { text: "Who has the most hidden talents?", textAr: "مين عنده مواهب مخفية أكثر من الكل؟", category: "achievements" },
  { text: "Who is most likely to win a competition they just entered?", textAr: "مين أكثر واحد يكسب مسابقة توّه داخلها؟", category: "achievements" },
  { text: "Who would give the best TED Talk?", textAr: "مين فينا بيطلع أحلى محاضرة قدام الناس؟", category: "achievements" },
  { text: "Who would win a trivia night?", textAr: "مين بيكسب لو سوّينا مسابقة معلومات؟", category: "achievements" },
  { text: "Who would be the best at a new skill after just one week?", textAr: "مين بيتعلّم مهارة جديدة ويتقنها بأسبوع واحد بس؟", category: "achievements" },
  { text: "Who would be featured in a \"30 under 30\" list?", textAr: "مين فينا يستاهل يدخل قائمة أنجح شباب تحت الثلاثين؟", category: "achievements" },
  { text: "Who would win a cooking competition?", textAr: "مين بيكسب لو صار فيه مسابقة طبخ؟", category: "achievements" },
  { text: "Who secretly practices things until they're perfect?", textAr: "مين اللي يتمرّن على الشي بالسر لين يضبطه عدل؟", category: "achievements" },
  { text: "Who would survive the longest on a deserted island?", textAr: "مين بيصمد أطول مدة لو انحبس بجزيرة خالية؟", category: "achievements" },
  { text: "Who is most likely to start a successful business?", textAr: "مين أكثر واحد ممكن يفتح مشروع وينجح فيه؟", category: "achievements" },
  { text: "Who would be the most decorated athlete in an alternate life?", textAr: "مين لو عاش حياة ثانية بيطلع أبطل رياضي وياخذ كل الميداليات؟", category: "achievements" },
  { text: "Who would build the most loyal following online?", textAr: "مين فينا بيجمّع له متابعين مخلصين على النت؟", category: "achievements" },
  { text: "Who would become a self-made success story?", textAr: "مين اللي بينجح بنفسه ويصير قصة كفاح؟", category: "achievements" },
  { text: "Who would win a talent show nobody expected them to enter?", textAr: "مين بيكسب برنامج مواهب وما كان أحد متوقّع إنه يشارك؟", category: "achievements" },
  { text: "Who is most likely to be remembered long after they're gone?", textAr: "مين فينا بيظل الناس يذكرونه حتى بعد ما يروح؟", category: "achievements" },
  { text: "Who would master a language in the shortest time?", textAr: "مين بيتقن لغة جديدة بأسرع وقت؟", category: "achievements" },
  { text: "Who would be the first to achieve something truly original?", textAr: "مين أول واحد فينا بيسوّي شي جديد وأصيل ما سوّاه أحد قبله؟", category: "achievements" },
  { text: "Who always finds a way to get what they want?", textAr: "مين دايم يلقى طريقة عشان يحصّل اللي يبيه؟", category: "achievements" },
  { text: "Who would be the most respected in their field?", textAr: "مين فينا بيكون أكثر واحد محترم بمجاله؟", category: "achievements" },
  { text: "Who would bounce back fastest after failure?", textAr: "مين أسرع واحد يرجع يقف على رجوله بعد ما يفشل؟", category: "achievements" },
  { text: "Who is most likely to get a standing ovation someday?", textAr: "مين أكثر واحد يوم من الأيام الناس بيقومون له ويصفّقون؟", category: "achievements" },
  { text: "Who learns by doing rather than studying?", textAr: "مين فينا يتعلّم بالتجربة مو بالمذاكرة؟", category: "achievements" },
  { text: "Who would be the most natural leader in a crisis?", textAr: "مين فينا بيطلع القائد لو صارت أزمة؟", category: "achievements" },
  { text: "Who has accomplished the most that nobody knows about?", textAr: "مين سوّى إنجازات وايد بس ما أحد يدري عنها؟", category: "achievements" },
  { text: "Who would write the most successful book?", textAr: "مين فينا لو كتب كتاب بيكون أنجح كتاب؟", category: "achievements" },
  { text: "Who would be the best mentor?", textAr: "مين أحسن واحد فينا يصير مرشد ويعلّم غيره؟", category: "achievements" },
  { text: "Who would win at whatever they put their mind to?", textAr: "مين اللي أي شي يحطّه ببالة بينجح فيه؟", category: "achievements" },
  { text: "Who would build something from nothing?", textAr: "مين فينا يقدر يبني شي من الصفر؟", category: "achievements" },
  { text: "Who is most driven by a goal they haven't told anyone about?", textAr: "مين عنده هدف بداخله وما قاله لأحد وهو شاغله؟", category: "achievements" },
  { text: "Who would be the most productive under pressure?", textAr: "مين أكثر واحد ينتج وينجز وقت الضغط؟", category: "achievements" },
  { text: "Who would inspire the most people without knowing it?", textAr: "مين فينا يلهم ناس وايد وهو حتى ما يدري؟", category: "achievements" },
  { text: "Who would get a promotion nobody saw coming?", textAr: "مين بيترقّى بشغله وما أحد كان متوقّع؟", category: "achievements" },
  { text: "Who would come out on top after the hardest year of their life?", textAr: "مين بيطلع أقوى بعد أصعب سنة بحياته؟", category: "achievements" },
  { text: "Who has the best work ethic in the group?", textAr: "مين فينا أكثر واحد جدّي ومجتهد بشغله؟", category: "achievements" },
  { text: "Who would be the most successful at reinventing themselves?", textAr: "مين أكثر واحد يقدر يغيّر نفسه من جديد وينجح؟", category: "achievements" },
  { text: "Who would be the most naturally gifted at something unexpected?", textAr: "مين فينا عنده موهبة فطرية بشي ما أحد يتوقّعه منه؟", category: "achievements" },
  { text: "Who would win a debate on a topic they just learned about?", textAr: "مين بيكسب نقاش عن موضوع توّه متعلّمه؟", category: "achievements" },
  { text: "Who is most likely to get a scholarship or award they barely applied for?", textAr: "مين أكثر واحد ياخذ ابتعاث أو جايزة وهو بالكاد قدّم لها؟", category: "achievements" },
  { text: "Who would be the most decorated person at their funeral (in the best way)?", textAr: "مين فينا يوم يروح الناس بيمدحونه ويذكرون أحلى الكلام عنه؟", category: "achievements" },
  { text: "Who has the most untapped potential?", textAr: "مين فينا عنده طاقة وإمكانيات وايد بس ما استغلّها؟", category: "achievements" },
  { text: "Who would run a marathon on three weeks' training?", textAr: "مين يقدر يجري ماراثون وهو متمرّن ثلاث أسابيع بس؟", category: "achievements" },
  { text: "Who would get the most done in a single hour?", textAr: "مين أكثر واحد ينجز أشياء وايد بساعة وحدة؟", category: "achievements" },
  { text: "Who would turn a hobby into a career?", textAr: "مين فينا يقدر يحوّل هوايته إلى مهنة؟", category: "achievements" },
  { text: "Who is most likely to be cited or quoted by someone in the future?", textAr: "مين أكثر واحد بالمستقبل الناس بينقلون كلامه ويقتبسون منه؟", category: "achievements" },
  { text: "Who would be the most celebrated person from this group at a reunion?", textAr: "مين فينا لو اجتمعنا بعد سنين بيكون أكثر واحد الكل يحتفي فيه؟", category: "achievements" },
  { text: "Who has already achieved something nobody in this room knows about?", textAr: "مين فينا سوّى إنجاز خلاص وما أحد بهالغرفة يدري عنه؟", category: "achievements" },
  { text: "Who would get the most done if they fully committed to something for 30 days?", textAr: "مين أكثر واحد بينجز لو التزم بشي كامل ثلاثين يوم؟", category: "achievements" },

  // 😬 Awkward (50)
  { text: "Who laughs at the worst possible moment?", textAr: "مين فينا يضحك في أسوأ وقت ممكن؟", category: "awkward" },
  { text: "Who would accidentally say something offensive without meaning to?", textAr: "مين فينا ممكن يطلّع كلمة تجرح من غير ما يقصد؟", category: "awkward" },
  { text: "Who waves back at someone who wasn't waving at them?", textAr: "مين اللي يرد السلام بإيده على واحد أصلاً ما كان يسلّم عليه؟", category: "awkward" },
  { text: "Who overshares with strangers?", textAr: "مين فينا يفتح قلبه ويحكي كل شي لناس ما يعرفهم؟", category: "awkward" },
  { text: "Who makes situations awkward without realizing it?", textAr: "مين أكثر واحد يخلي الجو محرج وهو ما حاس؟", category: "awkward" },
  { text: "Who answers \"you too\" when a waiter says \"enjoy your meal\"?", textAr: "مين اللي لما يقول له الجرسون \"بالعافية\" يرد عليه \"وأنت بعد\"؟", category: "awkward" },
  { text: "Who starts walking the same direction as someone they're saying goodbye to?", textAr: "مين اللي يودّع واحد وبعدها يطلع يمشي نفس طريقه؟", category: "awkward" },
  { text: "Who has held a door for someone who was too far away?", textAr: "مين فينا يمسك الباب لواحد لسّه بعيد عنه وايد؟", category: "awkward" },
  { text: "Who would give an accidental double-cheek kiss to someone expecting a handshake?", textAr: "مين اللي يبوس واحد على خده وهو أصلاً كان مادّ يده يسلّم بس؟", category: "awkward" },
  { text: "Who sends voice notes instead of typing?", textAr: "مين فينا يرسل فويسات بدال ما يكتب؟", category: "awkward" },
  { text: "Who starts laughing nervously during serious conversations?", textAr: "مين اللي تجيه ضحكة توتر في أجد المواضيع؟", category: "awkward" },
  { text: "Who would show up to the wrong address and knock anyway?", textAr: "مين اللي يوصل لعنوان غلط ومع ذلك يدق الباب؟", category: "awkward" },
  { text: "Who would accidentally call a teacher \"mum\"?", textAr: "مين اللي ممكن يقول للمدرّس \"يمّه\" من غير ما ينتبه؟", category: "awkward" },
  { text: "Who would try to recover from a social mistake and make it worse?", textAr: "مين اللي يحاول يصلّح غلطة محرجة ويخربها أكثر؟", category: "awkward" },
  { text: "Who would say \"same\" to something that doesn't apply to them at all?", textAr: "مين اللي يقول \"نفسي\" على شي أصلاً ما له فيه دخل؟", category: "awkward" },
  { text: "Who would arrive early to a party and be the only one there?", textAr: "مين اللي يجي الحفلة بدري ويلقى نفسه الوحيد اللي وصل؟", category: "awkward" },
  { text: "Who would start a story, realize it's going nowhere, and keep going anyway?", textAr: "مين اللي يبدأ يحكي قصة ويكتشف إنها ما لها طعم ويكمّل عادي؟", category: "awkward" },
  { text: "Who freezes when someone pays them an unexpected compliment?", textAr: "مين اللي يتجمّد لما أحد يمدحه فجأة؟", category: "awkward" },
  { text: "Who would awkwardly laugh when someone shares bad news?", textAr: "مين اللي يضحك ضحكة محرجة لما أحد يبلّغه خبر سيئ؟", category: "awkward" },
  { text: "Who would talk to fill silence and somehow make it more awkward?", textAr: "مين اللي يحكي عشان يكسر السكوت ويزيد الموقف حرج؟", category: "awkward" },
  { text: "Who would accidentally address someone by the wrong pronoun after being corrected?", textAr: "مين اللي ينادي واحد بالاسم الغلط حتى بعد ما صحّحوا له؟", category: "awkward" },
  { text: "Who would stand too close without realizing?", textAr: "مين اللي يقرّب على الناس وايد وهو ما حاس؟", category: "awkward" },
  { text: "Who would introduce themselves to someone they've already met?", textAr: "مين اللي يعرّف بنفسه على واحد أصلاً سبق وتعرّف عليه؟", category: "awkward" },
  { text: "Who would forget a birthday publicly and overcompensate?", textAr: "مين اللي ينسى عيد ميلاد قدام الكل وبعدها يبالغ عشان يعوّض؟", category: "awkward" },
  { text: "Who would respond to \"I love you\" with \"thanks\"?", textAr: "مين اللي لو قالوا له \"أحبك\" يرد \"مشكور\"؟", category: "awkward" },
  { text: "Who would start clapping when nobody else is?", textAr: "مين اللي يبدأ يصفّق وما حد غيره يصفّق؟", category: "awkward" },
  { text: "Who would say the wrong name at a critical moment?", textAr: "مين اللي يقول اسم غلط في أحرج لحظة؟", category: "awkward" },
  { text: "Who would misread the room so badly that everyone goes quiet?", textAr: "مين اللي يقرأ الجو غلط لدرجة إن الكل يسكت؟", category: "awkward" },
  { text: "Who would make eye contact with a stranger for too long?", textAr: "مين اللي يطوّل النظر في عيون واحد ما يعرفه؟", category: "awkward" },
  { text: "Who would try to make a joke at the wrong time and explain it?", textAr: "مين اللي يطقّ نكتة بوقت غلط وبعدها يشرحها؟", category: "awkward" },
  { text: "Who would confidently answer a question they completely misheard?", textAr: "مين اللي يجاوب على سؤال بكل ثقة وهو سامعه غلط؟", category: "awkward" },
  { text: "Who would call someone \"buddy\" when they can't remember their name?", textAr: "مين اللي ينادي واحد \"يا بطل\" لأنه ناسي اسمه؟", category: "awkward" },
  { text: "Who would say \"you too\" when someone says \"happy birthday\"?", textAr: "مين اللي لما يقولوا له \"كل عام وأنت بخير\" يرد \"وأنت بعد\"؟", category: "awkward" },
  { text: "Who would trip over nothing and fully acknowledge it?", textAr: "مين اللي يتعثّر على لا شي ويعترف إنه عثر؟", category: "awkward" },
  { text: "Who would hug someone who stuck their hand out for a handshake?", textAr: "مين اللي يحضن واحد وهو أصلاً مادّ يده يسلّم بس؟", category: "awkward" },
  { text: "Who would panic-text something that makes no sense?", textAr: "مين اللي يرسل رسالة على عجل ما لها معنى أصلاً؟", category: "awkward" },
  { text: "Who would tell a long joke and forget the punchline halfway through?", textAr: "مين اللي يبدأ نكتة طويلة وينسى آخرها بالنص؟", category: "awkward" },
  { text: "Who would try to make up a word and then defend it confidently?", textAr: "مين اللي يخترع كلمة من راسه وبعدها يدافع عنها بكل ثقة؟", category: "awkward" },
  { text: "Who would overstay their welcome at someone's house?", textAr: "مين اللي يطوّل قعدته في بيت أحد أكثر من اللازم؟", category: "awkward" },
  { text: "Who would agree with both sides of an argument to avoid conflict?", textAr: "مين اللي يوافق الطرفين في أي نقاش عشان ما يصير مشاكل؟", category: "awkward" },
  { text: "Who would laugh when they mean to look serious?", textAr: "مين اللي يبي يبيّن جاد ويطلع يضحك؟", category: "awkward" },
  { text: "Who would shake hands for way too long?", textAr: "مين اللي يطوّل السلام بالإيد أكثر من اللازم؟", category: "awkward" },
  { text: "Who would walk into a door they thought was automatic?", textAr: "مين اللي يصدم في باب وهو حاسبه يفتح أوتوماتيك؟", category: "awkward" },
  { text: "Who would say \"no worries\" six times in a row?", textAr: "مين اللي يقول \"عادي ولا يهمك\" ست مرات ورا بعض؟", category: "awkward" },
  { text: "Who would confuse someone's name with someone else's in their presence?", textAr: "مين اللي يخلط اسم واحد باسم ثاني وهو قاعد قدامه؟", category: "awkward" },
  { text: "Who would tell a personal story to someone who was already told it?", textAr: "مين اللي يعيد قصة شخصية على واحد أصلاً سبق وحكاها له؟", category: "awkward" },
  { text: "Who would mishear something important and nod as if they understood?", textAr: "مين اللي يسمع شي مهم غلط ويهز راسه كأنه فاهم؟", category: "awkward" },
  { text: "Who would bring up the most randomly uncomfortable topic at dinner?", textAr: "مين اللي يفتح أحرج موضوع وأغربه فجأة على سفرة العشا؟", category: "awkward" },
  { text: "Who would press the wrong floor in an elevator and ride it in silence?", textAr: "مين اللي يضغط دور غلط في المصعد ويقعد ساكت لين يوصل؟", category: "awkward" },
  { text: "Who would apologize for something that wasn't their fault five times?", textAr: "مين اللي يعتذر خمس مرات على شي أصلاً مو غلطه؟", category: "awkward" },

  // 🌶️ Bold (50)
  { text: "Who would speak their mind even if nobody asked?", textAr: "مين فينا يقول اللي في باله حتى لو ما حد سأله؟", category: "bold" },
  { text: "Who would quit their job on the spot if disrespected?", textAr: "مين فينا يترك شغله على طول لو حس إنهم ما يحترمونه؟", category: "bold" },
  { text: "Who would tell the host their party was bad?", textAr: "مين يقول لصاحب العزيمة بوجهه إن حفلته كانت سيئة؟", category: "bold" },
  { text: "Who has the most controversial opinions?", textAr: "مين فينا آراؤه تجيب مشاكل أكثر من غيره؟", category: "bold" },
  { text: "Who is most likely to go viral for saying something bold?", textAr: "مين أكثر واحد ممكن يصير ترند عشان قال كلام جريء؟", category: "bold" },
  { text: "Who would call out a stranger for being rude?", textAr: "مين يرد على واحد غريب ويعلّمه عشان قلة أدبه؟", category: "bold" },
  { text: "Who would tell a friend their partner is wrong for them?", textAr: "مين يقول لصاحبه بصراحة إن شريكه ما يناسبه؟", category: "bold" },
  { text: "Who would raise their hand when no one else will?", textAr: "مين يرفع يده لما ما حد يبي يرفعها؟", category: "bold" },
  { text: "Who would challenge the expert in the room?", textAr: "مين يتحدّى الخبير اللي قاعد بالمجلس ويناقشه؟", category: "bold" },
  { text: "Who would post an unpopular opinion and not delete it?", textAr: "مين ينشر رأي ما حد يبيه ويثبت عليه وما يحذفه؟", category: "bold" },
  { text: "Who would say \"actually, I disagree\" in a meeting?", textAr: "مين يقول \"بصراحة أنا مختلف معك\" قدام الكل بالاجتماع؟", category: "bold" },
  { text: "Who is most likely to start a movement?", textAr: "مين أكثر واحد ممكن يبدأ حركة ويلم الناس وراه؟", category: "bold" },
  { text: "Who would walk out of a bad movie and ask for a refund?", textAr: "مين يطلع من فيلم سيئ ويطلب فلوسه يرجعونها له؟", category: "bold" },
  { text: "Who would send back food at a restaurant?", textAr: "مين يرجّع الأكل بالمطعم لو ما عجبه؟", category: "bold" },
  { text: "Who would tell someone their idea is bad, kindly but directly?", textAr: "مين يقول لواحد إن فكرته ما تنفع، بأسلوب حلو بس على طول؟", category: "bold" },
  { text: "Who would end a conversation that wasn't serving them?", textAr: "مين يقطع السالفة على طول لو حس إنها ما تفيده؟", category: "bold" },
  { text: "Who has said something that changed how someone else saw things?", textAr: "مين قال كلمة غيّرت نظرة واحد ثاني للأمور؟", category: "bold" },
  { text: "Who would unmatch someone for a boring opener?", textAr: "مين يلغي الماتش مع واحد عشان بدايته كانت مملة؟", category: "bold" },
  { text: "Who would say what everyone else is thinking but won't say?", textAr: "مين يقول اللي الكل يفكر فيه بس ما حد يجرؤ يقوله؟", category: "bold" },
  { text: "Who would leave a one-star review with full detail?", textAr: "مين يحط تقييم نجمة وحدة ويكتب القصة كلها بالتفصيل؟", category: "bold" },
  { text: "Who would defend someone who's being left out?", textAr: "مين يدافع عن الشخص اللي يحاولون يستبعدونه ويطنشونه؟", category: "bold" },
  { text: "Who would confront a rumor directly instead of ignoring it?", textAr: "مين يواجه الإشاعة وجه لوجه بدل ما يطنشها؟", category: "bold" },
  { text: "Who would skip the small talk and go straight to the real conversation?", textAr: "مين يتجاوز الكلام الفاضي ويدخل بالموضوع الجد على طول؟", category: "bold" },
  { text: "Who would wear something bold to a formal event and own it?", textAr: "مين يلبس شي جريء بمناسبة رسمية ويتفلسف فيه بكل ثقة؟", category: "bold" },
  { text: "Who would start a petition for something they genuinely believe in?", textAr: "مين يبدأ حملة توقيعات عشان شي مؤمن فيه من قلبه؟", category: "bold" },
  { text: "Who would walk away from a group that no longer adds to their life?", textAr: "مين يمشي ويترك مجموعة ما عادت تضيف له شي؟", category: "bold" },
  { text: "Who would tell someone directly if they felt disrespected?", textAr: "مين يقول للشخص على طول لو حس إنه ما احترمه؟", category: "bold" },
  { text: "Who would admit a hot take in a room of people who disagree?", textAr: "مين يقول رأي جريء قدام ناس كلهم ضده؟", category: "bold" },
  { text: "Who would disagree with a popular opinion in a public forum?", textAr: "مين يخالف الرأي اللي الكل متفق عليه قدام الناس بالعلن؟", category: "bold" },
  { text: "Who would negotiate harder than anyone expected?", textAr: "مين يفاصل ويساوم أقوى من ما يتوقع أحد؟", category: "bold" },
  { text: "Who would give honest feedback on something people said was great?", textAr: "مين يقول رأيه بصراحة في شي الكل مدحه وقال عنه رهيب؟", category: "bold" },
  { text: "Who would start a hard conversation instead of letting it fester?", textAr: "مين يفتح السالفة الصعبة بدل ما يخليها تكبر وتزيد؟", category: "bold" },
  { text: "Who would call out favoritism without hesitation?", textAr: "مين يفضح المحسوبية والتفرقة من غير ما يتردد؟", category: "bold" },
  { text: "Who would speak the loudest in a situation where everyone goes quiet?", textAr: "مين يرفع صوته ويتكلم لما الكل يسكت؟", category: "bold" },
  { text: "Who would reject a job offer that didn't meet their worth?", textAr: "مين يرفض عرض وظيفة لأنه ما يساوي قيمته؟", category: "bold" },
  { text: "Who would push back when everyone else just agrees?", textAr: "مين يعترض ويرد لما الكل بس يقول أوكي وموافق؟", category: "bold" },
  { text: "Who would choose honesty over kindness when they had to pick one?", textAr: "مين يختار الصراحة على المجاملة لو لازم يختار وحدة؟", category: "bold" },
  { text: "Who would tell a story that exposes something uncomfortable about themselves?", textAr: "مين يحكي قصة تكشف عن نفسه شي محرج وما له داعي؟", category: "bold" },
  { text: "Who would be the first to say \"I think we're wrong about this\"?", textAr: "مين أول واحد يقول \"أحس إحنا غلطانين بهالشي\"؟", category: "bold" },
  { text: "Who would confront something that others pretend not to notice?", textAr: "مين يواجه شي الكل يتظاهر إنه ما لاحظه؟", category: "bold" },
  { text: "Who would ask the question that makes everyone uncomfortable?", textAr: "مين يسأل السؤال اللي يحرج الكل ويسكتهم؟", category: "bold" },
  { text: "Who would call a bluff?", textAr: "مين يكشف الواحد اللي يتفشخر ويبين كذبه؟", category: "bold" },
  { text: "Who would tell a white lie and then immediately correct it?", textAr: "مين يقول كذبة بيضاء وعلى طول يرجع ويصححها؟", category: "bold" },
  { text: "Who would stand by a decision even when it becomes unpopular?", textAr: "مين يثبت على قراره حتى لو الكل صار ضده؟", category: "bold" },
  { text: "Who would refuse to pretend everything is fine when it isn't?", textAr: "مين يرفض يتظاهر إن كل شي تمام وهو مو تمام؟", category: "bold" },
  { text: "Who would give a speech without notes and nail it?", textAr: "مين يلقي كلمة بدون ورقة ولا تحضير ويبدع فيها؟", category: "bold" },
  { text: "Who would call someone out by name in a group setting?", textAr: "مين ينادي على واحد باسمه ويحرجه قدام الجمعة؟", category: "bold" },
  { text: "Who would draw a line in the sand and actually hold it?", textAr: "مين يحط خط أحمر ويثبت عليه فعلاً؟", category: "bold" },
  { text: "Who would be the first to change their mind when shown a better argument?", textAr: "مين أول واحد يغير رأيه لما يجيه دليل أقوى؟", category: "bold" },
  { text: "Who would make an enemy by telling the truth?", textAr: "مين يسوّي له عدو عشان قال الصدق؟", category: "bold" },
]

export function getQuestionsByCategories(categoryIds: string[]): Question[] {
  if (categoryIds.length === 0) return QUESTIONS
  return QUESTIONS.filter(q => categoryIds.includes(q.category))
}

export function shuffleQuestions(questions: Question[]): Question[] {
  const arr = [...questions]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}
