import type { Question } from './types'

export const CATEGORIES = [
  { id: 'spicy', label: 'Spicy', emoji: '🔥' },
  { id: 'funny', label: 'Funny', emoji: '😂' },
  { id: 'deep', label: 'Deep', emoji: '🧠' },
  { id: 'chaotic', label: 'Chaotic', emoji: '💀' },
  { id: 'romantic', label: 'Romantic', emoji: '💘' },
  { id: 'achievements', label: 'Achievements', emoji: '🏆' },
  { id: 'awkward', label: 'Awkward', emoji: '😬' },
  { id: 'bold', label: 'Bold', emoji: '🌶️' },
]

export const QUESTIONS: Question[] = [
  // 🔥 Spicy (50)
  { text: 'Who would survive a reality TV show the longest?', category: 'spicy' },
  { text: 'Who has the most unread messages?', category: 'spicy' },
  { text: 'Who would ghost someone without feeling bad?', category: 'spicy' },
  { text: 'Who is most likely to have a secret they\'ve never told anyone?', category: 'spicy' },
  { text: 'Who would win in an argument against a stranger?', category: 'spicy' },
  { text: 'Who has sent the most regrettable text at 2am?', category: 'spicy' },
  { text: 'Who is most likely to have a situationship right now?', category: 'spicy' },
  { text: 'Who would be the most dangerous person to give power to?', category: 'spicy' },
  { text: 'Who could charm their way out of any situation?', category: 'spicy' },
  { text: 'Who is secretly holding a grudge?', category: 'spicy' },
  { text: 'Who has the messiest relationship history?', category: 'spicy' },
  { text: 'Who would be a terrible lawyer but win the case anyway?', category: 'spicy' },
  { text: 'Who has the most controversial search history?', category: 'spicy' },
  { text: 'Who is most likely to start drama at a party?', category: 'spicy' },
  { text: 'Who flirts without realizing they\'re doing it?', category: 'spicy' },
  { text: 'Who would betray the group for money?', category: 'spicy' },
  { text: 'Who has the most situational morals?', category: 'spicy' },
  { text: 'Who is most likely to date someone wildly out of the group\'s expectations?', category: 'spicy' },
  { text: 'Who would survive the longest in a cult before catching on?', category: 'spicy' },
  { text: 'Who has the most toxic trait they refuse to acknowledge?', category: 'spicy' },
  { text: 'Who has lied the most convincingly to get out of something?', category: 'spicy' },
  { text: 'Who would make the scariest villain?', category: 'spicy' },
  { text: 'Who gives advice they don\'t follow themselves?', category: 'spicy' },
  { text: 'Who would be the first to expose a group secret?', category: 'spicy' },
  { text: 'Who needs the most external validation?', category: 'spicy' },
  { text: 'Who would be the most manipulative without trying to be?', category: 'spicy' },
  { text: 'Who is most likely to slide into someone\'s DMs right now?', category: 'spicy' },
  { text: 'Who has had the most complicated friendship?', category: 'spicy' },
  { text: 'Who is most likely to have a double life nobody knows about?', category: 'spicy' },
  { text: 'Who would turn into a completely different person after one drink?', category: 'spicy' },
  { text: 'Who is the most passive-aggressive when upset?', category: 'spicy' },
  { text: 'Who would win a staring contest with anyone?', category: 'spicy' },
  { text: 'Who is most likely to be the villain in someone else\'s story?', category: 'spicy' },
  { text: 'Who is carrying the most unresolved feelings?', category: 'spicy' },
  { text: 'Who would be the most intimidating person in a negotiation?', category: 'spicy' },
  { text: 'Who would say "I told you so" the fastest?', category: 'spicy' },
  { text: 'Who has the highest body count of situationships?', category: 'spicy' },
  { text: 'Who would thrive the most on the attention of someone they don\'t even like?', category: 'spicy' },
  { text: 'Who is most likely to have a soft spot for someone terrible for them?', category: 'spicy' },
  { text: 'Who would win a game of psychological chess?', category: 'spicy' },
  { text: 'Who is most likely to have unfinished business with someone from their past?', category: 'spicy' },
  { text: 'Who holds grudges the longest?', category: 'spicy' },
  { text: 'Who would be most dangerous if they were actually angry?', category: 'spicy' },
  { text: 'Who is most likely to keep receipts on everyone?', category: 'spicy' },
  { text: 'Who would last the longest pretending everything is fine?', category: 'spicy' },
  { text: 'Who would be the most convincing liar in an interrogation?', category: 'spicy' },
  { text: 'Who has the most skeletons in their closet?', category: 'spicy' },
  { text: 'Who would snap the most dramatically?', category: 'spicy' },
  { text: 'Who is most likely to be the reason someone goes to therapy?', category: 'spicy' },
  { text: 'Who could make someone fall for them without even trying?', category: 'spicy' },

  // 😂 Funny (50)
  { text: 'Who laughs at their own jokes the most?', category: 'funny' },
  { text: 'Who would trip walking up to accept an award?', category: 'funny' },
  { text: 'Who would accidentally text the wrong person something embarrassing?', category: 'funny' },
  { text: 'Who takes the longest to get ready?', category: 'funny' },
  { text: 'Who is most likely to forget someone\'s name mid-conversation?', category: 'funny' },
  { text: 'Who would accidentally like a photo from 3 years ago?', category: 'funny' },
  { text: 'Who would order the wrong thing and eat it anyway?', category: 'funny' },
  { text: 'Who would get into a heated debate about something completely trivial?', category: 'funny' },
  { text: 'Who would get lost following GPS directions?', category: 'funny' },
  { text: 'Who has the most chaotic morning routine?', category: 'funny' },
  { text: 'Who would say something awkward during a toast?', category: 'funny' },
  { text: 'Who would wear pajamas to an event if they could?', category: 'funny' },
  { text: 'Who would walk into a glass door?', category: 'funny' },
  { text: 'Who has the funniest "I thought I had it under control" story?', category: 'funny' },
  { text: 'Who is most likely to burn water?', category: 'funny' },
  { text: 'Who would mispronounce something in front of an expert?', category: 'funny' },
  { text: 'Who would confidently give wrong directions to a tourist?', category: 'funny' },
  { text: 'Who would sneeze at the worst possible moment?', category: 'funny' },
  { text: 'Who would buy something they\'ve never used and leave it in a drawer forever?', category: 'funny' },
  { text: 'Who would talk during a movie and claim they weren\'t?', category: 'funny' },
  { text: 'Who is most likely to be the reason a group plan falls apart?', category: 'funny' },
  { text: 'Who would accidentally reply-all to an email?', category: 'funny' },
  { text: 'Who would try to fix something and make it significantly worse?', category: 'funny' },
  { text: 'Who would laugh at a funeral?', category: 'funny' },
  { text: 'Who would show up to the wrong address with full confidence?', category: 'funny' },
  { text: 'Who is most likely to auto-correct a message into something chaotic?', category: 'funny' },
  { text: 'Who would dramatically overreact to a bug?', category: 'funny' },
  { text: 'Who would fall asleep during an important event?', category: 'funny' },
  { text: 'Who would absolutely destroy everyone at karaoke?', category: 'funny' },
  { text: 'Who would lose track of time and show up an hour late, guilt-free?', category: 'funny' },
  { text: 'Who would challenge someone to a race and immediately regret it?', category: 'funny' },
  { text: 'Who would accidentally join the wrong group chat?', category: 'funny' },
  { text: 'Who is most likely to mispronounce a word they\'ve only ever read?', category: 'funny' },
  { text: 'Who would narrate their own life like a documentary?', category: 'funny' },
  { text: 'Who would eat something weird and ask what it was only after finishing?', category: 'funny' },
  { text: 'Who would try to be cool in front of a celebrity and completely fail?', category: 'funny' },
  { text: 'Who would panic-buy the most during a sale?', category: 'funny' },
  { text: 'Who would lose a staring contest in under 5 seconds?', category: 'funny' },
  { text: 'Who would sing out loud without realizing others can hear them?', category: 'funny' },
  { text: 'Who sends the most chaotic voice notes?', category: 'funny' },
  { text: 'Who would forget they asked a question and ask it again?', category: 'funny' },
  { text: 'Who has the most chaotic notes app?', category: 'funny' },
  { text: 'Who would arrive somewhere and immediately want to leave?', category: 'funny' },
  { text: 'Who would save every meme but never send them to anyone?', category: 'funny' },
  { text: 'Who would google something obvious and not tell anyone?', category: 'funny' },
  { text: 'Who has an embarrassing playlist they\'d die if anyone saw?', category: 'funny' },
  { text: 'Who would start a story with "this is so funny" and then tell a terrible story?', category: 'funny' },
  { text: 'Who would break something at someone\'s house and say nothing?', category: 'funny' },
  { text: 'Who would think they\'re whispering but absolutely aren\'t?', category: 'funny' },
  { text: 'Who would try to sneak food into somewhere and get caught immediately?', category: 'funny' },

  // 🧠 Deep (50)
  { text: 'Who thinks about life\'s meaning the most?', category: 'deep' },
  { text: 'Who would write a book someday?', category: 'deep' },
  { text: 'Who feels things more deeply than they show?', category: 'deep' },
  { text: 'Who is most likely to change the world?', category: 'deep' },
  { text: 'Who has the most complex inner world?', category: 'deep' },
  { text: 'Who questions everything they\'ve been taught?', category: 'deep' },
  { text: 'Who would be the most transformative teacher?', category: 'deep' },
  { text: 'Who carries the weight of other people\'s problems?', category: 'deep' },
  { text: 'Who is quietly figuring out their purpose?', category: 'deep' },
  { text: 'Who would be the wisest at age 80?', category: 'deep' },
  { text: 'Who has had the most formative life experience?', category: 'deep' },
  { text: 'Who sees patterns others miss?', category: 'deep' },
  { text: 'Who is most likely to have a profound conversation at 3am?', category: 'deep' },
  { text: 'Who thinks about their legacy the most?', category: 'deep' },
  { text: 'Who has the most well-developed moral code?', category: 'deep' },
  { text: 'Who would be the most introspective after a hard experience?', category: 'deep' },
  { text: 'Who has grown the most in the last few years?', category: 'deep' },
  { text: 'Who would give the best life advice to a stranger?', category: 'deep' },
  { text: 'Who is most in touch with who they really are?', category: 'deep' },
  { text: 'Who has the clearest sense of what they want from life?', category: 'deep' },
  { text: 'Who would be the most self-aware person in a therapy session?', category: 'deep' },
  { text: 'Who would forgive the hardest thing to forgive?', category: 'deep' },
  { text: 'Who is most likely to cry at something unexpected?', category: 'deep' },
  { text: 'Who notices things others don\'t pay attention to?', category: 'deep' },
  { text: 'Who would handle grief the most quietly?', category: 'deep' },
  { text: 'Who is carrying something they haven\'t said out loud yet?', category: 'deep' },
  { text: 'Who would write the most honest journal entry?', category: 'deep' },
  { text: 'Who has the most defined sense of home?', category: 'deep' },
  { text: 'Who is most likely to reinvent themselves completely?', category: 'deep' },
  { text: 'Who makes people feel the most seen?', category: 'deep' },
  { text: 'Who would be most at peace with an uncertain future?', category: 'deep' },
  { text: 'Who has the most nuanced opinions on complicated topics?', category: 'deep' },
  { text: 'Who would sit with their own silence the best?', category: 'deep' },
  { text: 'Who is most likely to choose meaning over money?', category: 'deep' },
  { text: 'Who grieves things that others move on from quickly?', category: 'deep' },
  { text: 'Who has the most unresolved inner conflict?', category: 'deep' },
  { text: 'Who would be the first to admit they were wrong?', category: 'deep' },
  { text: 'Who most deeply understands someone else in this group?', category: 'deep' },
  { text: 'Who would turn pain into something beautiful?', category: 'deep' },
  { text: 'Who is most likely to find profound meaning in small moments?', category: 'deep' },
  { text: 'Who would be the most honest in an autobiography?', category: 'deep' },
  { text: 'Who thinks the most about the people they\'ve lost touch with?', category: 'deep' },
  { text: 'Who is most likely to leave everything behind and start fresh?', category: 'deep' },
  { text: 'Who asks the best questions?', category: 'deep' },
  { text: 'Who feels most connected to something bigger than themselves?', category: 'deep' },
  { text: 'Who is most changed by the books or stories they consume?', category: 'deep' },
  { text: 'Who would understand a stranger\'s perspective the fastest?', category: 'deep' },
  { text: 'Who has the most considered relationship with their past?', category: 'deep' },
  { text: 'Who would be the hardest to truly know?', category: 'deep' },
  { text: 'Who will look back on this period of life the most fondly?', category: 'deep' },

  // 💀 Chaotic (50)
  { text: 'Who would start a fire (accidentally) at a party?', category: 'chaotic' },
  { text: 'Who makes decisions by flipping a coin?', category: 'chaotic' },
  { text: 'Who would show up to a formal event underdressed?', category: 'chaotic' },
  { text: 'Who is one bad day away from moving to another country?', category: 'chaotic' },
  { text: 'Who has the most chaotic phone camera roll?', category: 'chaotic' },
  { text: 'Who would agree to something without reading the fine print?', category: 'chaotic' },
  { text: 'Who would give terrible directions but be fully confident?', category: 'chaotic' },
  { text: 'Who would mix drinks at a party and call it a "signature cocktail"?', category: 'chaotic' },
  { text: 'Who would spontaneously adopt a pet?', category: 'chaotic' },
  { text: 'Who would start five projects and finish none of them?', category: 'chaotic' },
  { text: 'Who would reorganize a room and make it worse?', category: 'chaotic' },
  { text: 'Who would walk into the wrong room and just go with it?', category: 'chaotic' },
  { text: 'Who would quit their job on a random Tuesday with no backup plan?', category: 'chaotic' },
  { text: 'Who would book a flight on impulse?', category: 'chaotic' },
  { text: 'Who has the most unhinged notes in their phone?', category: 'chaotic' },
  { text: 'Who would rearrange everyone\'s furniture while they\'re sleeping?', category: 'chaotic' },
  { text: 'Who would make a major life decision based on a horoscope?', category: 'chaotic' },
  { text: 'Who would start a group project the night before?', category: 'chaotic' },
  { text: 'Who would forget where they parked and report their car stolen?', category: 'chaotic' },
  { text: 'Who is most likely to have three unfinished online shopping carts?', category: 'chaotic' },
  { text: 'Who would download 10 apps, use none of them, and delete them all?', category: 'chaotic' },
  { text: 'Who would let autocorrect send something truly unhinged?', category: 'chaotic' },
  { text: 'Who would wake up and immediately make a chaotic decision?', category: 'chaotic' },
  { text: 'Who would set five alarms and sleep through all of them?', category: 'chaotic' },
  { text: 'Who is most likely to take a random exit on a road trip and just see what happens?', category: 'chaotic' },
  { text: 'Who would impulse-buy something massive and regret it immediately?', category: 'chaotic' },
  { text: 'Who would RSVP yes to two conflicting events and deal with it later?', category: 'chaotic' },
  { text: 'Who would try to fix the Wi-Fi and accidentally reset everyone\'s settings?', category: 'chaotic' },
  { text: 'Who would go down a rabbit hole at 1am and emerge with a new obsession?', category: 'chaotic' },
  { text: 'Who would be the last to realize the plan changed?', category: 'chaotic' },
  { text: 'Who has the most "I can fix it" energy about things they can\'t fix?', category: 'chaotic' },
  { text: 'Who would start a diet on a Thursday?', category: 'chaotic' },
  { text: 'Who would confidently assemble furniture and have pieces left over?', category: 'chaotic' },
  { text: 'Who would invite too many people to something and not tell anyone?', category: 'chaotic' },
  { text: 'Who would get distracted on an errand and come back with something completely different?', category: 'chaotic' },
  { text: 'Who is most likely to lose their keys, wallet, and phone in the same day?', category: 'chaotic' },
  { text: 'Who would start redecorating at midnight?', category: 'chaotic' },
  { text: 'Who would "quickly check something" and disappear for 45 minutes?', category: 'chaotic' },
  { text: 'Who would name a pet something unhinged?', category: 'chaotic' },
  { text: 'Who would send a 3-minute voice note when a one-word answer was needed?', category: 'chaotic' },
  { text: 'Who is most likely to accidentally break something they just bought?', category: 'chaotic' },
  { text: 'Who would read a 5-step recipe and freestyle from step 2?', category: 'chaotic' },
  { text: 'Who would cancel plans, feel relieved, and then immediately make new plans?', category: 'chaotic' },
  { text: 'Who would save a spider in a cup and forget about it for three days?', category: 'chaotic' },
  { text: 'Who would get 40 tabs open and refuse to close any of them?', category: 'chaotic' },
  { text: 'Who would sign up for a class, go once, and never return?', category: 'chaotic' },
  { text: 'Who would move furniture alone at 11pm because they "couldn\'t sleep"?', category: 'chaotic' },
  { text: 'Who has sent the most unhinged group chat message?', category: 'chaotic' },
  { text: 'Who would start explaining something and completely lose track of the point?', category: 'chaotic' },
  { text: 'Who would order something entirely different from what they said they wanted?', category: 'chaotic' },

  // 💘 Romantic (50)
  { text: 'Who falls in love too easily?', category: 'romantic' },
  { text: 'Who would plan the most elaborate date?', category: 'romantic' },
  { text: 'Who is most likely to have a crush right now?', category: 'romantic' },
  { text: 'Who gives the best relationship advice but ignores it themselves?', category: 'romantic' },
  { text: 'Who would write love letters?', category: 'romantic' },
  { text: 'Who has the most romantic soul?', category: 'romantic' },
  { text: 'Who would put the most thought into a gift?', category: 'romantic' },
  { text: 'Who would say "I love you" first?', category: 'romantic' },
  { text: 'Who would stay up all night talking on a first date?', category: 'romantic' },
  { text: 'Who is most likely to have a Pinterest wedding board?', category: 'romantic' },
  { text: 'Who would serenade someone without a shred of embarrassment?', category: 'romantic' },
  { text: 'Who has the most romantic movie-worthy backstory?', category: 'romantic' },
  { text: 'Who would be most affected by a breakup?', category: 'romantic' },
  { text: 'Who would make the most effort to keep a long-distance relationship alive?', category: 'romantic' },
  { text: 'Who re-reads old messages from people they liked?', category: 'romantic' },
  { text: 'Who would be the best at making someone feel special on an ordinary day?', category: 'romantic' },
  { text: 'Who would plan a surprise that makes someone genuinely emotional?', category: 'romantic' },
  { text: 'Who would show up with flowers for no reason?', category: 'romantic' },
  { text: 'Who would remember the tiny details a partner mentioned months ago?', category: 'romantic' },
  { text: 'Who still believes in the idea of "the one"?', category: 'romantic' },
  { text: 'Who would make a playlist for someone they like?', category: 'romantic' },
  { text: 'Who would be the most heartbroken after a falling out with a close friend?', category: 'romantic' },
  { text: 'Who would cry at a romantic movie scene without admitting it?', category: 'romantic' },
  { text: 'Who would be the most devoted partner?', category: 'romantic' },
  { text: 'Who would love too much too fast?', category: 'romantic' },
  { text: 'Who notices small romantic gestures that others miss?', category: 'romantic' },
  { text: 'Who would choose a slow dance over a wild night out?', category: 'romantic' },
  { text: 'Who is most likely to fall for someone who is completely wrong for them?', category: 'romantic' },
  { text: 'Who would never settle for anything less than butterflies?', category: 'romantic' },
  { text: 'Who would be the most affectionate partner?', category: 'romantic' },
  { text: 'Who would keep a photo of someone they liked years after it ended?', category: 'romantic' },
  { text: 'Who would choose love over a career opportunity?', category: 'romantic' },
  { text: 'Who is most likely to get emotional over an anniversary?', category: 'romantic' },
  { text: 'Who would send the most thoughtful morning text?', category: 'romantic' },
  { text: 'Who would still be curious about an old flame?', category: 'romantic' },
  { text: 'Who would fall for someone who wasn\'t their usual type?', category: 'romantic' },
  { text: 'Who gives the best hugs?', category: 'romantic' },
  { text: 'Who has loved someone deeply but never told them?', category: 'romantic' },
  { text: 'Who would walk someone home just to spend more time with them?', category: 'romantic' },
  { text: 'Who values loyalty the most in a relationship?', category: 'romantic' },
  { text: 'Who would be the most patient with a difficult partner?', category: 'romantic' },
  { text: 'Who would plan a romantic picnic completely from scratch?', category: 'romantic' },
  { text: 'Who is most likely to say "I miss you" first?', category: 'romantic' },
  { text: 'Who would still get butterflies from a simple text?', category: 'romantic' },
  { text: 'Who would drop everything to be there for someone they love?', category: 'romantic' },
  { text: 'Who would be most affected by a song that reminds them of someone?', category: 'romantic' },
  { text: 'Who would make the most romantic grand gesture?', category: 'romantic' },
  { text: 'Who is most likely to marry their best friend?', category: 'romantic' },
  { text: 'Who would love harder than anyone expects?', category: 'romantic' },
  { text: 'Who would still believe in love after getting their heart broken?', category: 'romantic' },

  // 🏆 Achievements (50)
  { text: 'Who is most likely to become famous?', category: 'achievements' },
  { text: 'Who was (or still is) the teacher\'s favorite?', category: 'achievements' },
  { text: 'Who would be most successful in 10 years?', category: 'achievements' },
  { text: 'Who has the most hidden talents?', category: 'achievements' },
  { text: 'Who is most likely to win a competition they just entered?', category: 'achievements' },
  { text: 'Who would give the best TED Talk?', category: 'achievements' },
  { text: 'Who would win a trivia night?', category: 'achievements' },
  { text: 'Who would be the best at a new skill after just one week?', category: 'achievements' },
  { text: 'Who would be featured in a "30 under 30" list?', category: 'achievements' },
  { text: 'Who would win a cooking competition?', category: 'achievements' },
  { text: 'Who secretly practices things until they\'re perfect?', category: 'achievements' },
  { text: 'Who would survive the longest on a deserted island?', category: 'achievements' },
  { text: 'Who is most likely to start a successful business?', category: 'achievements' },
  { text: 'Who would be the most decorated athlete in an alternate life?', category: 'achievements' },
  { text: 'Who would build the most loyal following online?', category: 'achievements' },
  { text: 'Who would become a self-made success story?', category: 'achievements' },
  { text: 'Who would win a talent show nobody expected them to enter?', category: 'achievements' },
  { text: 'Who is most likely to be remembered long after they\'re gone?', category: 'achievements' },
  { text: 'Who would master a language in the shortest time?', category: 'achievements' },
  { text: 'Who would be the first to achieve something truly original?', category: 'achievements' },
  { text: 'Who always finds a way to get what they want?', category: 'achievements' },
  { text: 'Who would be the most respected in their field?', category: 'achievements' },
  { text: 'Who would bounce back fastest after failure?', category: 'achievements' },
  { text: 'Who is most likely to get a standing ovation someday?', category: 'achievements' },
  { text: 'Who learns by doing rather than studying?', category: 'achievements' },
  { text: 'Who would be the most natural leader in a crisis?', category: 'achievements' },
  { text: 'Who has accomplished the most that nobody knows about?', category: 'achievements' },
  { text: 'Who would write the most successful book?', category: 'achievements' },
  { text: 'Who would be the best mentor?', category: 'achievements' },
  { text: 'Who would win at whatever they put their mind to?', category: 'achievements' },
  { text: 'Who would build something from nothing?', category: 'achievements' },
  { text: 'Who is most driven by a goal they haven\'t told anyone about?', category: 'achievements' },
  { text: 'Who would be the most productive under pressure?', category: 'achievements' },
  { text: 'Who would inspire the most people without knowing it?', category: 'achievements' },
  { text: 'Who would get a promotion nobody saw coming?', category: 'achievements' },
  { text: 'Who would come out on top after the hardest year of their life?', category: 'achievements' },
  { text: 'Who has the best work ethic in the group?', category: 'achievements' },
  { text: 'Who would be the most successful at reinventing themselves?', category: 'achievements' },
  { text: 'Who would be the most naturally gifted at something unexpected?', category: 'achievements' },
  { text: 'Who would win a debate on a topic they just learned about?', category: 'achievements' },
  { text: 'Who is most likely to get a scholarship or award they barely applied for?', category: 'achievements' },
  { text: 'Who would be the most decorated person at their funeral (in the best way)?', category: 'achievements' },
  { text: 'Who has the most untapped potential?', category: 'achievements' },
  { text: 'Who would run a marathon on three weeks\' training?', category: 'achievements' },
  { text: 'Who would get the most done in a single hour?', category: 'achievements' },
  { text: 'Who would turn a hobby into a career?', category: 'achievements' },
  { text: 'Who is most likely to be cited or quoted by someone in the future?', category: 'achievements' },
  { text: 'Who would be the most celebrated person from this group at a reunion?', category: 'achievements' },
  { text: 'Who has already achieved something nobody in this room knows about?', category: 'achievements' },
  { text: 'Who would get the most done if they fully committed to something for 30 days?', category: 'achievements' },

  // 😬 Awkward (50)
  { text: 'Who laughs at the worst possible moment?', category: 'awkward' },
  { text: 'Who would accidentally say something offensive without meaning to?', category: 'awkward' },
  { text: 'Who waves back at someone who wasn\'t waving at them?', category: 'awkward' },
  { text: 'Who overshares with strangers?', category: 'awkward' },
  { text: 'Who makes situations awkward without realizing it?', category: 'awkward' },
  { text: 'Who answers "you too" when a waiter says "enjoy your meal"?', category: 'awkward' },
  { text: 'Who starts walking the same direction as someone they\'re saying goodbye to?', category: 'awkward' },
  { text: 'Who has held a door for someone who was too far away?', category: 'awkward' },
  { text: 'Who would give an accidental double-cheek kiss to someone expecting a handshake?', category: 'awkward' },
  { text: 'Who sends voice notes instead of typing?', category: 'awkward' },
  { text: 'Who starts laughing nervously during serious conversations?', category: 'awkward' },
  { text: 'Who would show up to the wrong address and knock anyway?', category: 'awkward' },
  { text: 'Who would accidentally call a teacher "mum"?', category: 'awkward' },
  { text: 'Who would try to recover from a social mistake and make it worse?', category: 'awkward' },
  { text: 'Who would say "same" to something that doesn\'t apply to them at all?', category: 'awkward' },
  { text: 'Who would arrive early to a party and be the only one there?', category: 'awkward' },
  { text: 'Who would start a story, realize it\'s going nowhere, and keep going anyway?', category: 'awkward' },
  { text: 'Who freezes when someone pays them an unexpected compliment?', category: 'awkward' },
  { text: 'Who would awkwardly laugh when someone shares bad news?', category: 'awkward' },
  { text: 'Who would talk to fill silence and somehow make it more awkward?', category: 'awkward' },
  { text: 'Who would accidentally address someone by the wrong pronoun after being corrected?', category: 'awkward' },
  { text: 'Who would stand too close without realizing?', category: 'awkward' },
  { text: 'Who would introduce themselves to someone they\'ve already met?', category: 'awkward' },
  { text: 'Who would forget a birthday publicly and overcompensate?', category: 'awkward' },
  { text: 'Who would respond to "I love you" with "thanks"?', category: 'awkward' },
  { text: 'Who would start clapping when nobody else is?', category: 'awkward' },
  { text: 'Who would say the wrong name at a critical moment?', category: 'awkward' },
  { text: 'Who would misread the room so badly that everyone goes quiet?', category: 'awkward' },
  { text: 'Who would make eye contact with a stranger for too long?', category: 'awkward' },
  { text: 'Who would try to make a joke at the wrong time and explain it?', category: 'awkward' },
  { text: 'Who would confidently answer a question they completely misheard?', category: 'awkward' },
  { text: 'Who would call someone "buddy" when they can\'t remember their name?', category: 'awkward' },
  { text: 'Who would say "you too" when someone says "happy birthday"?', category: 'awkward' },
  { text: 'Who would trip over nothing and fully acknowledge it?', category: 'awkward' },
  { text: 'Who would hug someone who stuck their hand out for a handshake?', category: 'awkward' },
  { text: 'Who would panic-text something that makes no sense?', category: 'awkward' },
  { text: 'Who would tell a long joke and forget the punchline halfway through?', category: 'awkward' },
  { text: 'Who would try to make up a word and then defend it confidently?', category: 'awkward' },
  { text: 'Who would overstay their welcome at someone\'s house?', category: 'awkward' },
  { text: 'Who would agree with both sides of an argument to avoid conflict?', category: 'awkward' },
  { text: 'Who would laugh when they mean to look serious?', category: 'awkward' },
  { text: 'Who would shake hands for way too long?', category: 'awkward' },
  { text: 'Who would walk into a door they thought was automatic?', category: 'awkward' },
  { text: 'Who would say "no worries" six times in a row?', category: 'awkward' },
  { text: 'Who would confuse someone\'s name with someone else\'s in their presence?', category: 'awkward' },
  { text: 'Who would tell a personal story to someone who was already told it?', category: 'awkward' },
  { text: 'Who would mishear something important and nod as if they understood?', category: 'awkward' },
  { text: 'Who would bring up the most randomly uncomfortable topic at dinner?', category: 'awkward' },
  { text: 'Who would press the wrong floor in an elevator and ride it in silence?', category: 'awkward' },
  { text: 'Who would apologize for something that wasn\'t their fault five times?', category: 'awkward' },

  // 🌶️ Bold (50)
  { text: 'Who would speak their mind even if nobody asked?', category: 'bold' },
  { text: 'Who would quit their job on the spot if disrespected?', category: 'bold' },
  { text: 'Who would tell the host their party was bad?', category: 'bold' },
  { text: 'Who has the most controversial opinions?', category: 'bold' },
  { text: 'Who is most likely to go viral for saying something bold?', category: 'bold' },
  { text: 'Who would call out a stranger for being rude?', category: 'bold' },
  { text: 'Who would tell a friend their partner is wrong for them?', category: 'bold' },
  { text: 'Who would raise their hand when no one else will?', category: 'bold' },
  { text: 'Who would challenge the expert in the room?', category: 'bold' },
  { text: 'Who would post an unpopular opinion and not delete it?', category: 'bold' },
  { text: 'Who would say "actually, I disagree" in a meeting?', category: 'bold' },
  { text: 'Who is most likely to start a movement?', category: 'bold' },
  { text: 'Who would walk out of a bad movie and ask for a refund?', category: 'bold' },
  { text: 'Who would send back food at a restaurant?', category: 'bold' },
  { text: 'Who would tell someone their idea is bad, kindly but directly?', category: 'bold' },
  { text: 'Who would end a conversation that wasn\'t serving them?', category: 'bold' },
  { text: 'Who has said something that changed how someone else saw things?', category: 'bold' },
  { text: 'Who would unmatch someone for a boring opener?', category: 'bold' },
  { text: 'Who would say what everyone else is thinking but won\'t say?', category: 'bold' },
  { text: 'Who would leave a one-star review with full detail?', category: 'bold' },
  { text: 'Who would defend someone who\'s being left out?', category: 'bold' },
  { text: 'Who would confront a rumor directly instead of ignoring it?', category: 'bold' },
  { text: 'Who would skip the small talk and go straight to the real conversation?', category: 'bold' },
  { text: 'Who would wear something bold to a formal event and own it?', category: 'bold' },
  { text: 'Who would start a petition for something they genuinely believe in?', category: 'bold' },
  { text: 'Who would walk away from a group that no longer adds to their life?', category: 'bold' },
  { text: 'Who would tell someone directly if they felt disrespected?', category: 'bold' },
  { text: 'Who would admit a hot take in a room of people who disagree?', category: 'bold' },
  { text: 'Who would disagree with a popular opinion in a public forum?', category: 'bold' },
  { text: 'Who would negotiate harder than anyone expected?', category: 'bold' },
  { text: 'Who would give honest feedback on something people said was great?', category: 'bold' },
  { text: 'Who would start a hard conversation instead of letting it fester?', category: 'bold' },
  { text: 'Who would call out favoritism without hesitation?', category: 'bold' },
  { text: 'Who would speak the loudest in a situation where everyone goes quiet?', category: 'bold' },
  { text: 'Who would reject a job offer that didn\'t meet their worth?', category: 'bold' },
  { text: 'Who would push back when everyone else just agrees?', category: 'bold' },
  { text: 'Who would choose honesty over kindness when they had to pick one?', category: 'bold' },
  { text: 'Who would tell a story that exposes something uncomfortable about themselves?', category: 'bold' },
  { text: 'Who would be the first to say "I think we\'re wrong about this"?', category: 'bold' },
  { text: 'Who would confront something that others pretend not to notice?', category: 'bold' },
  { text: 'Who would ask the question that makes everyone uncomfortable?', category: 'bold' },
  { text: 'Who would call a bluff?', category: 'bold' },
  { text: 'Who would tell a white lie and then immediately correct it?', category: 'bold' },
  { text: 'Who would stand by a decision even when it becomes unpopular?', category: 'bold' },
  { text: 'Who would refuse to pretend everything is fine when it isn\'t?', category: 'bold' },
  { text: 'Who would give a speech without notes and nail it?', category: 'bold' },
  { text: 'Who would call someone out by name in a group setting?', category: 'bold' },
  { text: 'Who would draw a line in the sand and actually hold it?', category: 'bold' },
  { text: 'Who would be the first to change their mind when shown a better argument?', category: 'bold' },
  { text: 'Who would make an enemy by telling the truth?', category: 'bold' },
]

export function getQuestionsByCategories(categoryIds: string[]): Question[] {
  if (categoryIds.length === 0) return QUESTIONS
  return QUESTIONS.filter(q => categoryIds.includes(q.category))
}

export function shuffleQuestions(questions: Question[]): Question[] {
  const arr = [...questions]
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]]
  }
  return arr
}
