import type { Lang } from './i18n'

// English is the source of truth. Arabic (Saudi colloquial) is filled in below.
// Any key missing from `ar` falls back to `en` automatically (see i18n.t).

const en: Record<string, string> = {
  back: 'Back',
  goHome: 'Go Home',
  loading: 'Loading...',
  roomNotFound: 'Room not found',
  tagline: 'Rated E for Everyone Gets Exposed.',
  setProfile: 'Set your profile',
  edit: 'Edit',
  createRoom: 'Create Room',
  joinRoom: 'Join Room',
  createdBy: 'Created By Ibra',
  settings: 'Settings',
  soundEffects: 'Sound Effects',
  soundDesc: 'Votes, reveals, timer & more',
  language: 'Language',
  languageDesc: 'App & question language',
  creatingRoom: 'Creating room...',
  roomCreated: 'Room Created!',
  shareCode: 'Share the code or QR with your friends',
  goToLobby: 'Go to Lobby',
  joinARoom: 'Join a Room',
  enterCodeOrScan: 'Enter the room code or scan the QR',
  enterCode: 'ENTER CODE',
  joining: 'Joining...',
  or: 'or',
  scanQR: 'Scan QR',
  uploadQR: 'Upload QR',
  codeMustBe6: 'Room code must be 6 characters',
  roomNotFoundRetry: 'Room not found. Check the code and try again.',
  gameAlreadyStarted: 'This game has already started.',
  qrReadFail: 'Could not read QR code from image.',
  lobby: 'Lobby',
  invite: 'Invite',
  hide: 'Hide',
  yourProfile: 'Your Profile',
  yourName: 'Your name...',
  nameFallback: 'Your name',
  scanQRTitle: 'Scan QR Code',
  scanQRHint: 'Point camera at the QR code',
  useUploadInstead: 'Use Upload QR Instead',
  copy: 'Copy',
  copied: 'Copied',
  scanOrEnterAt: 'Scan QR or enter code at',
  iconTab: 'Icon',
  colorTab: 'Color',
  fontTab: 'Font',
  saving: 'Saving...',
  saveProfile: 'Save Profile',
  players: 'Players',
  chooseCategories: 'Choose Categories',
  need2Players: 'Need at least 2 named players to start',
  waitingHostStart: 'Waiting for host to start the game...',
  gameSetup: 'Game Setup',
  numQuestions: 'Number of Questions',
  timerPerQ: 'Timer per Question',
  allowRevoting: 'Allow Revoting',
  revotingOn: 'Players can change their vote anytime — round ends on timer only.',
  revotingOff: 'First vote locks in — round ends as soon as everyone has voted.',
  on: 'On',
  off: 'Off',
  categories: 'Categories',
  allCategories: 'All Categories',
  allCategoriesDesc: 'Every type of question',
  randomMix: 'Random Mix',
  randomMixDesc: '4 random categories selected for you',
  customMode: 'Custom',
  customModeDesc: 'Hand-pick which categories to include',
  starting: 'Starting...',
  startGameTpl: 'Start Game · {n} questions 🎤',
  selectAtLeast1: 'Select at least 1 category',
  leave: 'Leave',
  votedCountTpl: '{n}/{m} voted',
  yourVoteIn: 'Your vote is in ✓',
  votedTapChange: 'Voted — tap to change',
  you: '(you)',
  results: 'Results',
  voteSingular: 'vote',
  votePlural: 'votes',
  calledOutTpl: '{name} was Called Out! 🎤',
  tiedTpl: '{names} tied! 🤝',
  nextQuestion: 'Next Question',
  seeFinalStats: 'See Final Stats',
  waitingHostContinue: 'Waiting for host to continue...',
  verdictIn: 'The Verdict Is In',
  howCalledOut: "Here's how your group was called out",
  wantPlayAgain: 'Want to play again?',
  iWantPlayAgain: 'I want to play again',
  playAgainQ: 'Play Again?',
  playersWantRoundTpl: '{n}/{m} players want another round',
  restartGame: 'Restart Game 🔄',
  endGame: 'End Game',
  leaveGame: 'Leave Game',
  leaveTheGame: 'Leave the game?',
  hostEndWarning: "You're the host — ending the game kicks everyone out.",
  removedFromSession: "You'll be removed from the session.",
  endForEveryone: 'End Game for Everyone',
  stayInGame: 'Stay in Game',
  aboutTagline: 'The party game where your friends decide who you really are.',
  aboutWhatBody:
    "Called Out is a mobile-first party game for groups. Everyone answers the same prompt by voting for whoever in the room fits it best. It's fast, a little chaotic, and best played out loud with people you don't mind roasting.",
  howToPlay: 'How to play',
  step1Title: 'Set up a room',
  step1Text: 'One person creates a room and shares the code. Everyone else joins on their own phone.',
  step2Title: 'Read the prompt',
  step2Text: 'Each round shows a "Who is most likely to…" style question across categories like Spicy, Funny, Deep and more.',
  step3Title: 'Vote it out',
  step3Text: 'Tap the person in the group the question fits best. Yes, you can vote for yourself. No judgement. (Okay, some judgement.)',
  step4Title: 'Get called out',
  step4Text: 'Votes are revealed and the most-voted person gets crowned for that round.',
  step5Title: 'Earn your title',
  step5Text: 'At the end, everyone is awarded a title based on how they were voted — from The Main Character to The Forgotten One.',
  goodToKnow: 'Good to know',
  tip1: 'Best with 3+ players, all in the same room.',
  tip2: 'The host can pick categories, question count and round timer in setup.',
  tip3: 'Turn on Allow Revoting to let people change their pick until the timer runs out.',
  contactIbra: 'Contact Ibra',
  cat_spicy: 'Spicy',
  cat_funny: 'Funny',
  cat_deep: 'Deep',
  cat_chaotic: 'Chaotic',
  cat_romantic: 'Romantic',
  cat_achievements: 'Achievements',
  cat_awkward: 'Awkward',
  cat_bold: 'Bold',
  title_main_character: 'The Main Character',
  title_sleeper: 'The Sleeper',
  title_wildcard: 'The Wildcard',
  title_predictably: 'Predictably You',
  title_their_own_fan: 'Their Own Biggest Fan',
  title_menace: 'The Menace',
  title_class_clown: 'Class Clown',
  title_philosopher: 'The Philosopher',
  title_chaotic: 'Certified Chaotic',
  title_romantic: 'The Hopeless Romantic',
  title_legend: 'The Legend',
  title_cringe: 'Captain Cringe',
  title_daredevil: 'The Daredevil',
  title_mysterious: 'The Mysterious One',
  title_forgotten: 'The Forgotten One',
  sub_main_character: 'Most voted overall — {n} votes',
  sub_sleeper: 'Quiet overall, but stole {n} rounds outright',
  sub_wildcard: 'In the mix for {n} rounds, rarely the clear pick',
  sub_predictably: 'Called out in {n} of {m} rounds',
  sub_their_own_fan: '{n} of their {m} votes were self-cast',
  sub_menace: 'Trouble seems to follow you everywhere',
  sub_class_clown: "The group's certified comedian",
  sub_philosopher: 'The one everyone calls deep',
  sub_chaotic: 'Reigning champion of pure chaos',
  sub_romantic: 'Your name came up every time love did',
  sub_legend: 'Built different — the group MVP',
  sub_cringe: 'Master of the unforgettable awkward moment',
  sub_daredevil: 'No dare too wild, no line uncrossed',
  sub_mysterious: 'Flew under the radar all game',
  sub_forgotten: 'Not a single vote. Not even from themselves.',
}

// Saudi colloquial Arabic — populated from the translation pass.
const ar: Record<string, string> = {
  "back": "رجوع",
  "goHome": "الرئيسية",
  "loading": "يحمّل...",
  "roomNotFound": "الغرفة مو موجودة",
  "tagline": "مصنّف +18… لأن الكل بينفضح.",
  "setProfile": "جهّز بروفايلك",
  "edit": "تعديل",
  "createRoom": "سوِّ غرفة",
  "joinRoom": "ادخل غرفة",
  "createdBy": "Created By Ibra",
  "settings": "الإعدادات",
  "soundEffects": "المؤثرات الصوتية",
  "soundDesc": "التصويت، الكشف، المؤقّت وأكثر",
  "language": "اللغة",
  "languageDesc": "لغة التطبيق والأسئلة",
  "creatingRoom": "يسوّي الغرفة...",
  "roomCreated": "صارت الغرفة!",
  "shareCode": "شارك الكود أو الـ QR مع شلتك",
  "goToLobby": "روح للوبي",
  "joinARoom": "ادخل غرفة",
  "enterCodeOrScan": "اكتب كود الغرفة أو امسح الـ QR",
  "enterCode": "اكتب الكود",
  "joining": "يدخّلك...",
  "or": "أو",
  "scanQR": "امسح QR",
  "uploadQR": "ارفع QR",
  "codeMustBe6": "كود الغرفة لازم 6 خانات",
  "roomNotFoundRetry": "الغرفة مو موجودة. تأكد من الكود وحاول مرة ثانية.",
  "gameAlreadyStarted": "اللعبة بدأت من زمان.",
  "qrReadFail": "ما قدرنا نقرأ الـ QR من الصورة.",
  "lobby": "اللوبي",
  "invite": "عزّم",
  "hide": "إخفاء",
  "yourProfile": "بروفايلك",
  "nameFallback": "اسمك",
  "scanQRTitle": "امسح كود الـ QR",
  "scanQRHint": "وجّه الكاميرا على الـ QR",
  "useUploadInstead": "استخدم رفع الـ QR بدالها",
  "copy": "نسخ",
  "copied": "تم النسخ",
  "scanOrEnterAt": "امسح الـ QR أو اكتب الكود في",
  "yourName": "اسمك...",
  "iconTab": "أيقونة",
  "colorTab": "لون",
  "fontTab": "خط",
  "saving": "يحفظ...",
  "saveProfile": "احفظ البروفايل",
  "players": "اللاعبين",
  "chooseCategories": "اختر التصنيفات",
  "need2Players": "لازم لاعبين على الأقل عندهم أسماء عشان تبدأ",
  "waitingHostStart": "ننتظر المضيف يبدأ اللعبة...",
  "gameSetup": "إعداد اللعبة",
  "numQuestions": "عدد الأسئلة",
  "timerPerQ": "وقت كل سؤال",
  "allowRevoting": "السماح بتغيير الصوت",
  "revotingOn": "اللاعبين يقدرون يغيّرون صوتهم بأي وقت — الجولة تخلص بس مع المؤقّت.",
  "revotingOff": "أول صوت يثبّت — الجولة تخلص أول ما يصوّت الكل.",
  "on": "تشغيل",
  "off": "إيقاف",
  "categories": "التصنيفات",
  "allCategories": "كل التصنيفات",
  "allCategoriesDesc": "كل أنواع الأسئلة",
  "randomMix": "خلطة عشوائية",
  "randomMixDesc": "4 تصنيفات عشوائية مختارة لك",
  "customMode": "مخصّص",
  "customModeDesc": "اختر بنفسك أي تصنيفات تبي",
  "starting": "يبدأ...",
  "startGameTpl": "ابدأ اللعبة · {n} سؤال 🎤",
  "selectAtLeast1": "اختر تصنيف واحد على الأقل",
  "leave": "طلوع",
  "votedCountTpl": "صوّت {n}/{m}",
  "yourVoteIn": "صوتك انحسب ✓",
  "votedTapChange": "صوّتت — اضغط عشان تغيّر",
  "you": "(أنت)",
  "results": "النتائج",
  "voteSingular": "صوت",
  "votePlural": "أصوات",
  "calledOutTpl": "{name} انفضح! 🎤",
  "tiedTpl": "{names} تعادلوا! 🤝",
  "nextQuestion": "السؤال الجاي",
  "seeFinalStats": "شوف النتائج النهائية",
  "waitingHostContinue": "ننتظر المضيف يكمّل...",
  "verdictIn": "طلع الحكم",
  "howCalledOut": "شوف كيف انفضحت شلتك",
  "wantPlayAgain": "تبون تلعبون مرة ثانية؟",
  "iWantPlayAgain": "أبي ألعب مرة ثانية",
  "playAgainQ": "نلعب مرة ثانية؟",
  "playersWantRoundTpl": "{n}/{m} يبون جولة ثانية",
  "restartGame": "أعد اللعبة 🔄",
  "endGame": "إنهاء اللعبة",
  "leaveGame": "اطلع من اللعبة",
  "leaveTheGame": "تطلع من اللعبة؟",
  "hostEndWarning": "أنت المضيف — إنهاء اللعبة بيطلّع الكل برا.",
  "removedFromSession": "بتنطرد من الجلسة.",
  "endForEveryone": "أنهِ اللعبة للكل",
  "stayInGame": "كمّل باللعبة",
  "aboutTagline": "لعبة السواليف اللي فيها شلتك يقررون مين أنت بصراحة.",
  "aboutWhatBody": "Called Out لعبة سواليف للجماعات على الجوال. كل واحد يجاوب على نفس السؤال ويصوّت لأكثر واحد بالغرفة ينطبق عليه. سريعة وفيها شوية فوضى، وأحلى ما تلعبها بصوت عالي مع ناس ما يهمّك تستهبل عليهم.",
  "howToPlay": "كيف تلعب",
  "step1Title": "جهّز غرفة",
  "step1Text": "واحد يسوّي غرفة ويشارك الكود، والباقي يدخلون من جوالاتهم.",
  "step2Title": "اقرأ السؤال",
  "step2Text": "كل جولة يطلع سؤال على طريقة «مين أكثر واحد...» من تصنيفات زي حار، مضحك، عميق وغيرها.",
  "step3Title": "صوّت",
  "step3Text": "اضغط على الشخص اللي ينطبق عليه السؤال أكثر. إي، تقدر تصوّت لنفسك. ما فيه أحكام. (طيب، فيه شوية أحكام.)",
  "step4Title": "انفضح",
  "step4Text": "تنكشف الأصوات، واللي جاب أكثر أصوات يتتوّج بطل الجولة.",
  "step5Title": "حصل لقبك",
  "step5Text": "بالنهاية كل واحد ياخذ لقب حسب التصويت — من بطل القصة إلى المنسي.",
  "goodToKnow": "معلومات تنفعك",
  "tip1": "أحلى ما تكون مع 3 لاعبين أو أكثر، كلكم بنفس المكان.",
  "tip2": "المضيف يقدر يختار التصنيفات وعدد الأسئلة ووقت الجولة من الإعدادات.",
  "tip3": "شغّل السماح بتغيير الصوت عشان الناس تقدر تغيّر اختيارها لين يخلص الوقت.",
  "contactIbra": "تواصل مع إبرا",
  "cat_spicy": "حار",
  "cat_funny": "مضحك",
  "cat_deep": "عميق",
  "cat_chaotic": "فوضوي",
  "cat_romantic": "رومنسي",
  "cat_achievements": "إنجازات",
  "cat_awkward": "محرج",
  "cat_bold": "جريء",
  "title_main_character": "بطل القصة",
  "title_sleeper": "الحصان الأسود",
  "title_wildcard": "المفاجأة",
  "title_predictably": "متوقّع منك",
  "title_their_own_fan": "أكبر معجب بنفسه",
  "title_menace": "المشكلجي",
  "title_class_clown": "مهرّج الشلة",
  "title_philosopher": "الفيلسوف",
  "title_chaotic": "فوضوي معتمد",
  "title_romantic": "الرومنسي الميؤوس منه",
  "title_legend": "الأسطورة",
  "title_cringe": "كابتن المواقف المحرجة",
  "title_daredevil": "اللي ما يخاف",
  "title_mysterious": "الغامض",
  "title_forgotten": "المنسي",
  "sub_main_character": "أكثر واحد صوّتوا له بالكامل — {n} صوت",
  "sub_sleeper": "هادي على العموم، بس خطف {n} جولات لحاله",
  "sub_wildcard": "كان داخل بالحسبة في {n} جولات، بس نادر يكون الاختيار الواضح",
  "sub_predictably": "انفضح في {n} من {m} جولات",
  "sub_their_own_fan": "{n} من {m} أصواته كانت لنفسه",
  "sub_menace": "المشاكل تلاحقك وين ما رحت",
  "sub_class_clown": "كوميديان الشلة المعتمد",
  "sub_philosopher": "اللي الكل يقول عنه عميق",
  "sub_chaotic": "بطل الفوضى بلا منازع",
  "sub_romantic": "اسمك يطلع كل ما جت سيرة الحب",
  "sub_legend": "مصنوع من طينة ثانية — نجم الشلة",
  "sub_cringe": "أستاذ المواقف المحرجة اللي ما تننسى",
  "sub_daredevil": "ما فيه تحدّي صعب عليه، ولا خط ما تعدّاه",
  "sub_mysterious": "عدّى تحت الرادار طول اللعبة",
  "sub_forgotten": "ولا صوت واحد. ولا حتى من نفسه.",
}

export const STRINGS: Record<Lang, Record<string, string>> = { en, ar }
